### ISSUE TITLE
Google oauth JWT 401 unauthorized

### ISSUE THREAD

**Issue by ManishJainGitHubUser** [khellang/Middleware#1]
Hello,
Can you confirm that this google jwt auth working with aspnet core 2.1? I am still getting 401 unauthorized.

**Comment by khellang** [comment]
Yes, I'm using it for a 2.1 app myself. What does the logs say?

**Comment by khellang** [comment]
Remember, you need to pass the `id_token` (which is a JWT) and not the `access_token` obtained from Google's OpenID Connect endpoints. https://developers.google.com/identity/protocols/OpenIDConnect

**Comment by ManishJainGitHubUser** [comment]
This now works. This is the only solution on the web that worked for me. Thank you. Thank you. :)

**Comment by khellang** [comment]
Glad it worked for you! 👍
