### ISSUE TITLE
ProblemDetails: support resolving ProblemDetailsOptions from service collection

### ISSUE THREAD

**Issue by StevenLiekens** [khellang/Middleware#10]
A popular way to use IOptions is to register them with the IServiceCollection and let DI take care of injecting options into middleware. ProblemDetailsOptions does not support this pattern right now because UseProblemDetails() always provides its own instance of IOptions.

To support DI, there should be a parameterless UseProblemDetails() that doesn't call `Options.Create()`

```diff
public static IApplicationBuilder UseProblemDetails(this IApplicationBuilder app)
{
-     var options = new ProblemDetailsOptions();

-     ConfigureDefaults(options);

-    return app.UseMiddleware<ProblemDetailsMiddleware>(Options.Create(options));
+    return app.UseMiddleware<ProblemDetailsMiddleware>();
}
```

It should be immediately obvious that this change creates a new issue: it's now impossible to do ConfigureDefaults inside the extension method.

One possible solution is to move ConfigureDefaults to an extension for IServiceCollection

```csharp
public static AddProblemDetails(this IServiceCollection services)
{
    services.Configure<ProblemDetailsOptions>(ConfigureDefaults); 
}

public static AddProblemDetails(this IServiceCollection services, Action<ProblemDetailsOptions> configure)
{
    services.Configure<ProblemDetailsOptions>(configure); 
    services.PostConfigure<ProblemDetailsOptions>(ConfigureDefaults);
}
```

**Comment by StevenLiekens** [comment]
Basic usage would then involve 2 lines of code instead of 1.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddProblemDetails();
}

public void Configure(IApplicationBuilder app)
{
    services.UseProblemDetails();
}
```

Although it might be possible to detect that no call to `AddProblemDetails` was made and fallback to the old behavior with Options.Create(0.

**Comment by khellang** [comment]
Yeah, I've gone back and forth on this. I thought about doing it, but I don't see any big advantage over the current solution. It's just more code (an extra call to `services.AddProblemDetails()`) to write, and the middleware doesn't really need to add any services. Want to convince me otherwise? 👼

**Comment by khellang** [comment]
> Although it might be possible to detect when no call to `AddProblemDetails` was made and fallback to the old behavior with Options.Create(0.

I do this with the SpaFallback middleware;

https://github.com/khellang/Middleware/blob/d38a1765e9524e5bf78d97684fb053d16460e8ff/src/SpaFallback/SpaFallbackExtensions.cs#L49-L50

https://github.com/khellang/Middleware/blob/d38a1765e9524e5bf78d97684fb053d16460e8ff/src/SpaFallback/SpaFallbackExtensions.cs#L65-L76

**Comment by StevenLiekens** [comment]
My issue started with the desire to have my problem configuration in a separate file.

First I created a static class for it.

```csharp
public static class ProblemConfigurer
{
    public static void Configure(ProblemDetailsOptions options)
    {
        ...
    }
}

// usage
public void Configure(IApplicationBuilder app)
{
    services.UseProblemDetails(ProblemConfigurer.Configure);
}
```

Then I quickly realized that I need my own dependencies inside ProblemConfigurer. It's impossible to do that via DI since it's a static class. There is a workaround, but the code is not very pleasant.

```csharp
// DI workaround
public void Configure(IApplicationBuilder app, IService1 dep1, IService2 dep2)
{
    services.UseProblemDetails(options => ProblemConfigurer.Configure(options, dep1, dep2));
}
```

But ultimately I'd like to convert my ProblemConfigurer to non-static and register it with DI so I can just have seamless dependency injection.

**Comment by khellang** [comment]
Hmm. I guess I could find a way to support both, without breaking people. I.e. you won't *have to* call `AddProblemDetails`, but you could if you want to use DI for configuration.

**Comment by khellang** [comment]
Pushed [v2.1.0](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails/2.1.0). Allowed myself to make a tiny breaking change by obsoleting the old `UseProblemDetails` method since literally no one has downloaded the 2.0.0 package yet 😝

**Comment by StevenLiekens** [comment]
Works great, thanks!
