### ISSUE TITLE
406 supposed to send ProblemDetails?

### ISSUE THREAD

**Issue by mkrajew** [khellang/Middleware#100]
I just added your ProblemDetails middleware and it works great, however I'm not getting a ProblemDetails object back for 406 errors.  Is this something that's supposed to happen with the defaults?  

I'm new to .NET core and tried configuring it further, but I didn't know what exception to catch and map to a 406. Mainly I implemented this because my Swagger/OpenAPI documentation was reporting that many of my API's error status codes were returning a ProblemDetails object when they were not, so I found your middleware which would actually return them.  Thanks!

**Comment by khellang** [comment]
The middleware should convert all 4xx and 5xx status codes to problem details responses, as well as all exceptions (whether they're mapped or not). People have had issue with 406 responses before, but that was related to their setup. Without more information, like some debug logs, i dont think i can be of much help. See https://github.com/khellang/Middleware/issues/54 for the previous 406 issue.

**Comment by mkrajew** [comment]
Thanks for that link. Just knowing that it's specific-enough to my project is good enough to know I haven't configured your project incorrectly and it's something else. 

I'm seeing 

> Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Warning: No output formatter was found for content types 'application/json' to write the response.
> 
> Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Warning: No output formatter was found for content types 'application/problem+json, application/problem+xml, application/problem+xml' to write the response.

whenever I execute the incorrect accept type that generates the 406. That led me down the path of  the `[Produces("application/json')]` attribute I have set for my API. I didn't know I may also need to include `application/problem+json` as well, but that leads to a few other issues [19510 ](https://github.com/dotnet/aspnetcore/issues/19510)and [18891](https://github.com/dotnet/aspnetcore/issues/18891). 

So I think I'm just going to be content knowing that I think it's set up properly. Thanks for your help.
