### ISSUE TITLE
Allow injecting IServiceProvider into `AddProblemDetails` action

### ISSUE THREAD

**Issue by coolhome** [khellang/Middleware#106]
We should be be able to expose the `IServiceProvider` from `IConfigureOptions` concrete classes. This will allow for a more dynamic range of configuration.

e.g.
```cs
services.AddProblemDetails( (provider, options) =>
{
    options.IncludeExceptionDetails = (context, exception) => provider.GetRequiredService<Something>().IsDebugMode;
});
```

**Comment by khellang** [comment]
Yeah, that could work, but this is already possible by registering your own implementation of `IConfigureOptions<ProblemDetailsOptions>`, like this:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsExtensions.cs#L36

**Comment by khellang** [comment]
Also, in the case of `IncludeExceptionDetails` (and most other predicate options), you have access to `HttpContext.RequestServices`, which allows you to do the same, without any additional classes and registrations 😊

**Comment by coolhome** [comment]
@khellang I do not know how I missed the HttpContext in that `IncludeExceptionDetails` 😃 Great information and thanks for the response.

I thought it would be nice to mimic what `AddHttpClient` is doing and allow passing in the provider. The only benefit I can think of is having full control but I guess implementing IConfigureOptions likely makes more sense. I don't see any way to get the provider when doing something like `serviceProvider.Configure<MyOptions>()`.
