### ISSUE TITLE
Not too sure how to migrate off ExceptionProblemDetails

### ISSUE THREAD

**Issue by PureKrome** [khellang/Middleware#107]
G'day 👋🏻 

I'm migrating to v5 and noticed this warning about `ExceptionProblemDetails` becoming obsolete.

![image](https://user-images.githubusercontent.com/899878/90643191-a2965180-e276-11ea-8019-6f6acc55e270.png)

(note: ignore the code in the image, i just wanted to quickly take a screenie 😊 )

Old:
```
options.Map<ValidationException>(validationException => 
    new ExceptionProblemDetails(validationException, StatusCodes.Status400BadRequest));
```

New:
```
options.Map<ValidationException>(validationException => 
                    new ValidationProblemDetails(validationException.Errors.ToDictionary(key => key.PropertyName, value => new string[] { value.ErrorMessage }))
                    {
                        Status = (int)HttpStatusCode.BadRequest
                    });
```

I just feel that the updated way I'm doing/trying is .. cumbersome? 

Would love some thoughts...

**Comment by khellang** [comment]
> I just feel that the updated way I'm doing/trying is .. cumbersome?

Sure, but it's not equivalent. The old code wouldn't even include the validation errors, right? 🤔

**Comment by khellang** [comment]
The equivalent of the old code would be to just map the validation exception to a 400 status code problem details, as the obsoletion message mentions 😅

**Comment by PureKrome** [comment]
> The equivalent of the old code would be to just map the validation exception to a 400 status code problem details, as the obsoletion message mentions

Ok - I should have mentioned i tried that _first_ but that doesn't allow us to include any error _info_. Which is why I thought there might be a trick to doing this, with your library?

**Comment by khellang** [comment]
> Which is why I thought there might be a trick to doing this, with your library?

Right, so I would probably do what you did, but I usually have either my own sub-type of `ProblemDetails` and do the mapping in the constructor, or some mapping method that cleans it up a bit.

**Comment by PureKrome** [comment]
Could you please paste an example of this ... I don't full 'see' it, in my head

🙏🏻

**Comment by khellang** [comment]
See https://github.com/khellang/Conference/blob/87b757276dfc7305613f0481449b43c20a25ab12/Conference/Startup.cs#L67 and https://github.com/khellang/Conference/blob/87b757276dfc7305613f0481449b43c20a25ab12/Conference/ValidationProblemDetails.cs 😄

**Comment by PureKrome** [comment]
Okay - this totally gets to my question 👍🏻 

So you created a new Property (called `Errors`) which would then get serialized when this class is serlialized-to-json when the json response payload is getting generatored/returned.

Ah! I thought we had to use _the provided_ `ProblemDetails` classes .. and not create our own ... which inherit from a PD .. which is this:

![image](https://user-images.githubusercontent.com/899878/90727947-71199680-e307-11ea-8f0f-daedc16d3612.png)


My reasoning was that I thought the _structure_ of a `ProblemDetails` is fixed. You can't change the schema.
So .. having a quick [read of the IETF RFC7807](https://tools.ietf.org/html/rfc7807#page-3) has:

- [section 3,1](https://tools.ietf.org/html/rfc7807#section-3.1) : Common members/properties of the json object. 
- [section 3.2](https://tools.ietf.org/html/rfc7807#section-3.2) : extension members  <--- custom properties which might help explain the problem in more detail.

Awesome - you've totally helped answer this.

Now - to update the readme ... oh ... dang... that's for another day, kind sir :)

**Comment by khellang** [comment]
Yes, the RFC only dictates the standard members. You can extend it as you like. The RFC even includes an example, which I've also used in the sample app:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/samples/ProblemDetails.Sample/Program.cs#L134-L161

**Comment by khellang** [comment]
> Ah! I thought we had to use _the provided_ `ProblemDetails` classes .. and not create our own

Yeah, there is a slight problem with inheriting from `ProblemDetails` and adding extra properties because of how MVC handles the difference between System.Text.Json and Newtonsoft.Json's `JsonExtensionData` attributes. That's why I switched from custom sub-types to just adding stuff to the `Extensions` dictionary in this library. I don't think that's a big issue if you don't mix and match serializers though.

**Comment by PureKrome** [comment]
> which I've also used in the sample app:

AH! i new I've read that  balance thing, before :) I was lazily thinking: "the money ATM balance thing must be a common use case people use in many examples...."

> That's why I switched from custom sub-types to just adding stuff to the Extensions dictionary in this library

`Extensions` dictionary? huh? Now you've lost me ??? ...

**Comment by khellang** [comment]
> `Extensions` dictionary? huh? Now you've lost me ??? ...

If you look at your screenshot above, you can see a property called `Extensions`, which is just a property bag that System.Text.Json (or Newtonsoft.Json) will include as regular JSON properties when serialized. This means you can also do stuff like this to add "properties", without a custom (sub-)type:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/DeveloperProblemDetailsExtensions.cs#L17

**Comment by PureKrome** [comment]
AH! i was looking at your SNIPPET above .. not the image i pasted. 

but the examples in the thread (above) are NOT using that `Extensions` property. So those samples are old, and now u're using that property instead?

**Comment by khellang** [comment]
> So those samples are old, and now u're using that property instead?

I'm using `Extensions` (as opposed to a sub-type) in this library because I have to support apps using both Newtonsoft.Json and System.Text.Json. In apps (like the sample), you can do whatever you want, as long as it gives you the output you'd like 😄

**Comment by PureKrome** [comment]
Hi @khellang - sorry to keep 'cast raise dead' on this topic, but I'm still struggling with it. I'm still trying to upgrade from 3.x to 5.1.1 and still getting some weird discrepancies - mainly the CASING of the 'custom properties'.

Here's some before/after sample responses:

(currently on live)
```
{
  "errors": {
    "statusTypes": [
      "The value 'foo' is not valid."
    ]
  },
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-3fc8b33309c203478d5005c87fb1c35b-46a5b975f80bc046-00"
}
```

(with 5.1.1. in a branch)
```
{
  "type": "https://httpstatuses.com/400",
  "title": "Bad Request",
  "status": 400,
  "errors": {
    "Age": [
      "too old."
    ],
    "Account": [
      "not enough funds."
    ]
  },
  "traceId": "00-310e4da8dc601e46b063e6bd838f3353-b46639fdae4d354a-00"
}
```

mainly notice `Age` and `Account` are not camel-cased. I just assumed that all items in the `Extensions` will get properly cased?

here's the code I ended up using (for 5.1.1):

```

services.AddProblemDetails(options =>
{
    //options.IncludeExceptionDetails = (httpContext, exception) => includeExceptionDetails;
    options.IncludeExceptionDetails = (httpContext, exception) => false;

    options.Map<ValidationException>(validationException =>
    {
        var problemDetails = new StatusCodeProblemDetails(StatusCodes.Status400BadRequest);
        problemDetails.Extensions["errors"] = validationException.Errors.ToDictionary(key => key.PropertyName, value => new string[] { value.ErrorMessage });

        return problemDetails;
    });
});
```

and the `ValidationException` is from `FluentValidation`.

**Comment by khellang** [comment]
What JSON serialization are you using? The MW is just using whatever settings you MVC app is using 😊

**Comment by khellang** [comment]
If you're using System.Text.Json, it might not camelCase the extensions properly. That might've changed since, but I had to do this to make it work properly; https://github.com/khellang/Conference/blob/87b757276dfc7305613f0481449b43c20a25ab12/Conference/ValidationProblemDetails.cs

**Comment by PureKrome** [comment]
While I'm trying to confirm the serializer (i'm sure it's Newtonsoft because the project is a bit older) ... is there any reason why that `ValidationProblemDetails` class can't be added to the Middleware, considering it's like .. really really reusable?

I know it's easy to 'copy/paste' etc but I would want to be using that in .. basically all API projects that will _also_ be using your middleware.

Maybe the name is too specific. But that fact that it:
- has an `Errors` property
- can accept a Dictionary

is really really helpful and reusable IMO.

/mg goes back to checking what the code is setup to do...

**Comment by PureKrome** [comment]
I'm using this: https://github.com/Homely/Homely.AspNetCore.Mvc.Helpers/blob/0ea02920e5ca67728199d3e2541b281d9ca197d6/src/Homely.AspNetCore.Mvc.Helpers/Extensions/IMvcBuilderExtensions.cs#L61

So it's using the new `System.Text.Json` serializer. Interesting...

**Comment by khellang** [comment]
> is there any reason why that `ValidationProblemDetails` class can't be added to the Middleware, considering it's like .. really really reusable?

What do you mean by "added to the Middleware"?

**Comment by khellang** [comment]
Ah, are you referring to [this](https://github.com/khellang/Conference/blob/87b757276dfc7305613f0481449b43c20a25ab12/Conference/ValidationProblemDetails.cs)? I can't really add that to this library as it's specific to the validation library, i.e. FluentValidation 😄

**Comment by PureKrome** [comment]
Nope, I was thinking about adding in a something like this:

(excuse the name .. it might be named something more generic..)

```
    public class ErrorProblemDetails: StatusCodeProblemDetails
    {
        public ErrorProblemDetails(IEnumerable<IDictionary<string, string> errors) : base(StatusCodes statusCode = StatusCode.Status422UnprocessableEntity)
        {
            ....
        }

        public IDictionary<string, string> Errors { get; }
    }
``` 

which could be totally reusable.

**Comment by PureKrome** [comment]
also @khellang  - i think the issue of the Dictionary not serializing correctly is due to a [known bug ](https://github.com/dotnet/runtime/issues/1197) which is fixed for a 5.0 release.

**Comment by khellang** [comment]
Yeah, the problem with `DictionaryKeyPolicy` is that it applies to *all* dictionaries, which could introduce problems with round-tripping. There is an issue for handling `JsonExtensionData` specifically, but that hasn't moved anywhere; https://github.com/dotnet/runtime/issues/31167.

**Comment by khellang** [comment]
I'm not sure a class like that would add a lot of value. The bulk of the code for validation errors would still be in the mapping from a validation exception into the dictionary, which you'd still need to write.
