### ISSUE TITLE
Bearer error="invalid_token", error_description="The signature is invalid"

### ISSUE THREAD

**Issue by xz013** [khellang/Middleware#109]
Hello i got this error : 

Bearer error="invalid_token", error_description="The signature is invalid"

*I have check my tokens with http get and works fine and  here is my code : 

 services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(jwt => jwt.UseGoogle(
        clientId: "Client ID",
        hostedDomain: "http://Mysite.com"
       ));

 
            services.AddAuthorization(options =>
            {
                options.DefaultPolicy = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme)
                    .RequireAuthenticatedUser()
                    .Build();
            });

 my con......

 [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {....}

------------------------------------------
my token

"eyJhbGciOiJSUzI1NiIsImtpZCI6ImQwNWVmMjBjNDUxOTFlZmY2NGIyNWQzODBkNDZmZGU1NWFjMjI5ZDEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4MzQwNDc3MjUwNDAtNTU0MDAxM243cWJxNjk4Z2dqdjk1aTlyazFsa2R2MDQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4MzQwNDc3MjUwNDAtNWIzcnVrZm9iY2x1cThxazJrM2NuMzVibjN2cHYwcjYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDAzMDYzMTQyNzgyNDA2NDIwMTAiLCJlbWFpbCI6InNlb2dyb3VwMTEyMjMzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiTW9oYW1lZCBFenphdCIsInBpY3R1cmUiOiJodHRwczovL2xoNi5nb29nbGV1c2VyY29udGVudC5jb20vLXZHaUtnZ2FpOVlVL0FBQUFBQUFBQUFJL0FBQUFBQUFBQUFBL0FNWnV1Y2tlSXdYMUJnbHJMcTVyX2ZrbXJsSWlTbVBGZkEvczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6Ik1vaGFtZWQiLCJmYW1pbHlfbmFtZSI6IkV6emF0IiwibG9jYWxlIjoiYXIiLCJpYXQiOjE2MDM2OTIxMzMsImV4cCI6MTYwMzY5NTczM30.lYxqKUbv59Vyuf0IUvfihgPtewi6X9OoWmopAJCHWj_5v1idUpJsPW_Ugf0mlZYwSG2zfr0bUhDuCx_eQ3f4-R1jlPlPDYfx4L0Ak78irKRkHAMTjSn3OzJnMzeElA3_rsjYRE48w-UJ2h409c00XjCXQ-oDpNo3EvFfn_sfJDai_8xUgk1k_iDZevEcw0OsZZf6zWMJy5b3"

any idea what is wrong and how to fix it !

**Comment by khellang** [comment]
I'm not sure. The signature seems invalid, but I have no idea why. See https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQwNWVmMjBjNDUxOTFlZmY2NGIyNWQzODBkNDZmZGU1NWFjMjI5ZDEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4MzQwNDc3MjUwNDAtNTU0MDAxM243cWJxNjk4Z2dqdjk1aTlyazFsa2R2MDQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4MzQwNDc3MjUwNDAtNWIzcnVrZm9iY2x1cThxazJrM2NuMzVibjN2cHYwcjYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDAzMDYzMTQyNzgyNDA2NDIwMTAiLCJlbWFpbCI6InNlb2dyb3VwMTEyMjMzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiTW9oYW1lZCBFenphdCIsInBpY3R1cmUiOiJodHRwczovL2xoNi5nb29nbGV1c2VyY29udGVudC5jb20vLXZHaUtnZ2FpOVlVL0FBQUFBQUFBQUFJL0FBQUFBQUFBQUFBL0FNWnV1Y2tlSXdYMUJnbHJMcTVyX2ZrbXJsSWlTbVBGZkEvczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6Ik1vaGFtZWQiLCJmYW1pbHlfbmFtZSI6IkV6emF0IiwibG9jYWxlIjoiYXIiLCJpYXQiOjE2MDM2OTIxMzMsImV4cCI6MTYwMzY5NTczM30.lYxqKUbv59Vyuf0IUvfihgPtewi6X9OoWmopAJCHWj_5v1idUpJsPW_Ugf0mlZYwSG2zfr0bUhDuCx_eQ3f4-R1jlPlPDYfx4L0Ak78irKRkHAMTjSn3OzJnMzeElA3_rsjYRE48w-UJ2h409c00XjCXQ-oDpNo3EvFfn_sfJDai_8xUgk1k_iDZevEcw0OsZZf6zWMJy5b3&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr1Y%2FvVjJTNpwgKDFx%2F%2BW%0AptOqvBPiivDU8%2Fi5BRiVJblOrKH5lM7XhJO%2FZP1NDAqWEmKKA9jw321Re7PEogPh%0ASZqyCASiwufN6%2Fs33HhhL1Lgv6knYOFaTRtpnPw8e0xG8yda%2FLP5HQUGcG50N7R%2F%0AF2vAKyXBTjgCzoLVtrngajoo3J8SZcjc2HyJyExC6ybe4rZo71vz%2F%2BvzENr1fGv4%0Ajk%2BTBLQgSK%2FSogOFpKRbVF3dFXZ%2F%2BrULygMyGJFm%2BWNCaunEo6NDXcgFNaHZd797%0AskXHYAgdO2wqw4r5P1p8kW2qMKukp5kEctYwNc0JCXoyclt9%2BzfJnerIBITlnAtk%0AQwIDAQAB%0A-----END%20PUBLIC%20KEY-----%0A

**Comment by xz013** [comment]
thank you for answer me , because of your help  found the wrong , 
it's back to android studio , I coped token from print console and it's have limit , 
now it's works good thank you for helping me ,

do you know how inject token after check it to my system like 

if user not register make for him an account with google like normally logging with google 

just when I write those lines get information of user : 
var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
var Email = await _userManager.GetEmailAsync(await _userManager.GetUserAsync(User));

**Comment by khellang** [comment]
When a user authenticates using a Google JWT, you can access the claims using the GoogleClaimTypes in this library, like

```csharp
User.FindFirstValue(GoogleClaimTypes.Email);
```

See https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/Authentication.JwtBearer.Google/GoogleClaimTypes.cs#L67-L70.

If the user doesn't exist, you can create it in your gontroller 😊

**Comment by xz013** [comment]
very thank you for your answer, 
the point is i'm using AspNetUsers

so how i can get user id , AspNetUsers genrate it , so I'm asking if there any method I can call it with user info to can create an account for me 

i hope you can got my point and really big thank you for helping me

**Comment by khellang** [comment]
It's a bit out of scope for this repo and there's probably a lot of info about this elsewhere, but I think it's just a matter of calling [`UserManager.CreateAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.createasync?view=aspnetcore-3.1#Microsoft_AspNetCore_Identity_UserManager_1_CreateAsync__0_System_String_) or [`SignInManager`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.signinasync?view=aspnetcore-3.1#Microsoft_AspNetCore_Identity_SignInManager_1_SignInAsync__0_System_Boolean_System_String_)?

**Comment by xz013** [comment]
really big thank you for helping me |
