### ISSUE TITLE
Multi JwtBearer Token

### ISSUE THREAD

**Issue by xz013** [khellang/Middleware#110]
Hello again , 

have another problem , hope you can helping me again .

have 2 audience 1 for android and another for iOS  so how i can use multi  audience

have tried it but got error : 

  services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
          .AddJwtBearer(x => x.UseGoogle(
        clientId: audience))
          .AddJwtBearer(x => x.UseGoogle(
        clientId: audienceios));
 

Error : 
System.InvalidOperationException: 'Scheme already exists: Bearer'

there any tricks how to do it !

**Comment by khellang** [comment]
Hey @xz013! I haven't tested this, but I think you can specify multiple audiences using something like this:

```csharp
services.AddAuthentication().AddJwtBearer(x =>
{
    x.UseGoogle(clientId: null);
    x.TokenValidationParameters.ValidAudiences = new[]
    {
        "clientId1",
        "clientId2",
    };
});
```

By passing `null` as the `clientId`, it should detect that it should use the `ValidAudiences` property instead of the regular `ValidAudience` property:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/Authentication.JwtBearer.Google/JwtBearerOptionsExtensions.cs#L61-L63

This is where the fallback happens:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a55020dba088171882bc3b4da3882772dd6ff3d2/src/Microsoft.IdentityModel.Tokens/Validators.cs#L122-L127

**Comment by khellang** [comment]
Nevermind, that won't work as we're checking for `null` and throwing. I think you'd have to do something like

```csharp
services.AddAuthentication().AddJwtBearer(jwt =>
{
    jwt.UseGoogle("clientId1");
    jwt.TokenValidationParameters.ValidAudiences = new[]
    {
        "clientId2",
    };
});
```

This will make it end up in the `else` block of the code linked above, which will validate against both client IDs.

I think we can leave this issue open as a feature request to add some overloads that allow you to specify multiple client IDs.

**Comment by khellang** [comment]
Another options could be to [use multiple authentication schemes](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1#use-multiple-authentication-schemes). That would also allow you to differentiate between the Android and iOS apps in authorization, i.e. only let the Android app access certain endpoints or perform certain actions.

**Comment by xz013** [comment]
really big thank you for answer me : 





i got this error : 

InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId, Android, iOS. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?

when using : 


services.AddAuthentication()
    .AddJwtBearer("Android", x => x.UseGoogle("android-client-id"))
    .AddJwtBearer("iOS", x => x.UseGoogle("ios-client-id"));


any idea how to solve it !

**Comment by xz013** [comment]
i add this and still got error : 

 services.AddAuthorization(options =>
            {
                
                options.DefaultPolicy = new AuthorizationPolicyBuilder( "Android", "iOS")
                    .RequireAuthenticatedUser()
                    .Build();
            });

and still got same error

**Comment by khellang** [comment]
That looks good to me, but I think this is going pretty far outside the scope of this repo and into the realm of StackOverflow 😉

**Comment by xz013** [comment]
really thank you for helping me and i hope you can add method for apple like you did with google , we need smart developer like you make word for us more easy , and really thank you for helping me
