### ISSUE TITLE
Validate access token

### ISSUE THREAD

**Issue by BenjaminWang1031** [khellang/Middleware#111]
Hey there,

Is it able to validate an access token?
I've tried with GoogleJwtBearerDefaults.AuthenticationScheme and got this error:

`System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).`

**Comment by khellang** [comment]
Can you show your code?

**Comment by BenjaminWang1031** [comment]
```
            services.AddAuthentication(GoogleJwtBearerDefaults.AuthenticationScheme)
                    .AddJwtBearer(jwt => jwt.UseGoogle(
                        clientId: "yourapp.googleusercontent.com"));
```
According to the source code, GoogleJwtBearerDefaults.AuthenticationScheme should be "Google.Bearer", right?

**Comment by BenjaminWang1031** [comment]
If we could pass that... my next question would be: how does that work since google access_token is not event a JwtBearer token?

**Comment by khellang** [comment]
> If we could pass that... my next question would be: how does that work since google access_token is not event a JwtBearer token?

Yeah, the `JwtBearer` handler can't validate `access_token`, it validates the `id_token` :)

**Comment by BenjaminWang1031** [comment]
> What happens if you just use JwtBearerDefaults.AuthenticationScheme as the default scheme? I'm not sure if the AddJwtBearer call picks up the scheme set in UseGoogle.

Since access token is not jwt, it always returns an invalid_token error,

Your package works perfectly for id_token validation, I think we have to use id_token if you want to use google oauth in swagger & .net core3.1, worse part is swaggerui always returns access_token and won't allow you to override it with id token.

So workaround is you pass id_token to api and protected by google(use your package to validate jwt), but for swagger ui, only allows user to enter a bearer token instead of trying to hookup to google login/oauths.

**Comment by khellang** [comment]
> worse part is swaggerui always returns access_token and won't allow you to override it with id token.

It's a hack, but I actually managed to get it working once:

```csharp
services.AddSwaggerGen(swagger =>
{
    var scopes = new Dictionary<string, string>
    {
        { "openid", "Authenticate using OpenID Connect" },
        { "profile", "View your basic profile info" },
        { "email", "View your email address" },
    };

    swagger.AddSecurityDefinition(JwtBearerDefaults.AuthenticationScheme, new OAuth2Scheme
    {
        Type = "oauth2",
        Flow = "implicit",
        AuthorizationUrl = "https://accounts.google.com/o/oauth2/v2/auth",
        TokenUrl = "https://oauth2.googleapis.com/token",
        Scopes = scopes,
        Extensions =
        {
            { "x-tokenName", "id_token" } // <-- This is part of the magic.
        },
    });

    swagger.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> 
    {
        { JwtBearerDefaults.AuthenticationScheme, scopes.Keys }
    });

    // The rest of your configuration in here...
});
```

Then, when adding Swagger UI:

```csharp
app.UseSwaggerUI(options =>
{
    options.OAuthAppName("<your-app-name>");
    options.OAuthClientId("<your-client-id>");
    options.InjectJavascript("/swagger-ui-openid.js");
    options.OAuthAdditionalQueryStringParams(new Dictionary<string, string>
    {
        { "nonce", Guid.NewGuid().ToString("n") }
    });
});
```

Then, include the following static file, `swagger-ui-openid.js` in your `wwwroot`:

```js
/* This is a huge hack to enable OpenID Connect in Swagger UI. See https://github.com/swagger-api/swagger-ui/issues/3906 */
window.open=function(e){return function(n){return e.call(window,n.replace("response_type=token","response_type=id_token"))}}(window.open);
```

It's around two years since I wrote this, so I have no clue whether it still works or if some kind of official support has been added since, but it did work at the time 😅

**Comment by khellang** [comment]
BTW, it looks like newer versions of Swashbuckle and swagger-ui support `x-tokenName` properly; https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1128

**Comment by BenjaminWang1031** [comment]
> BTW, it looks like newer versions of Swashbuckle and swagger-ui support x-tokenName properly; domaindrivendev/Swashbuckle.AspNetCore#1128

Sadly, it does not work, already tried...

I am going to try your hack way... that static js file might be the game changer!

**Comment by BenjaminWang1031** [comment]
My man! You just made my day!!
After a couple of days with researches and struggles, this is the first working solution for me with Google oauth2& SwaggerUI5.

Thank you!

**Comment by khellang** [comment]
Awesome! Glad I was able to help 😁 I assume this issue can ble closed, then?

**Comment by BenjaminWang1031** [comment]
Yes, for sure!
