### ISSUE TITLE
Is there any way to get to the Exception while inside OnBeforeWriteDetails? 

### ISSUE THREAD

**Issue by liquidsnk** [khellang/Middleware#113]
I'm not sure if that would be the best option to achieve what I want, but it seemed promising until I got stuck on how to get the exception instance.

Basically I want to add an additional extension property to the ProblemDetails instance, indicating some sort of internal error code. 
That error code comes from a property in the exception (if the exception is of certain type I'm interested in).
Is there a way to get to the exception instance from the HttpContext at this point? Do I have any other options to go about this?

**Comment by khellang** [comment]
> I'm not sure if that would be the best option to achieve what I want, but it seemed promising until I got stuck on how to get the exception instance.

Yeah, `OnBeforeWriteDetails` is called _after_ the exception (or status code) has been mapped to a `ProblemDetails` instance, right before it's written to the response stream.

> That error code comes from a property in the exception (if the exception is of certain type I'm interested in).

This sounds like you could just map the exception how you'd like, like this:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsOptions.cs#L133

In theory, we could modify `IncludeExceptionDetails` to also include the mapped result (we don't today), which would give you a hook to access both the exception and the `ProblemDetails` instance.

**Comment by liquidsnk** [comment]
> This sounds like you could just map the exception how you'd like, like this:
> 
> https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsOptions.cs#L133
> 
Awesome!, this is exactly what I needed, don't know how I didn't saw it. Thank you!
