### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by paulvanbladel** [khellang/Middleware#115]
Very nice project !
Simple question, can this library also help when I want to foresee a custom problem detail for a 401 (not authorized). 
In my understanding this library can intervene in problem details which are generated by user code.
Is there a simple way to patch the problem detail for a 401?
Thanks a million
cheers
paul.

**Comment by khellang** [comment]
Hi @paulvanbladel! 👋

I'm not 100% sure what you're asking, but the middleware is meant to handle all error conditions - from a status code or an exception. There are ways to configure both, but I think you're looking for `MapStatusCode`:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsOptions.cs#L88-L93

It should let you handle 401 status codes however you want 😊

**Comment by khellang** [comment]
There's also the `OnBeforeWriteDetails` hook, which i called after mapping has been performed, right before writing to the response:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsOptions.cs#L95-L99

Either of those would probably solve your problem 😊

**Comment by michael-gaudet** [comment]
I just discovered ProblemDetails yesterday after reading [this article](https://codeopinion.com/http-api-problem-details-in-asp-net-core/) (a bit old now, tbf) and just ran into the same question! 

Returning `Unauthorized()` is beautifully simple, but there's no overload to specify any `Detail` text about what might have gone wrong.

As a workaround, I tried implementing a class inheriting from `ProblemDetails` (with the additional text) and using the `throw new ProblemDetailsException(details)`. Unfortunately even when I set the `ProblemDetails` `Status` to `401` the actual response status code is still `500`.

I suppose I could create a custom exception type and use the options to map that exception to the `401` code, but I'm not quite clear on how you could use the two hooks above to handle a response in, say, a filter.

**Comment by paulvanbladel** [comment]
Christian, 
Brilliant,
The MapStatusCode wasn't working on my side but it's because i'm using ApiController attribute.
SuppressMapClientErrors = true solved that :
```
services.AddControllers().ConfigureApiBehaviorOptions(o =>
            {
                o.SuppressMapClientErrors = true;
            });
```

**Comment by paulvanbladel** [comment]
@michael-gaudet Maybe you want to model a 403.
Basically you will normally never use Unauthorized in code, that's normally captured by the authentication middleware.
So, it only happens when there is something wrong with the token.
The stuff you handle via code is normally via about authorization and should return a 403 (forbidden).

Apart from that, I think there an overload on Unauthorized where you can return a problem detail.

**Comment by khellang** [comment]
@paulvanbladel  Ah, yes, I normally always set `SuppressMapClientErrors` as I want the middleware to handle the problem details responses, not MVC 😊

@michael-gaudet Hmm, that could actually be a bug. I think the middleware should respect the status you set on the `ProblemDetails` instance. You could also create a separate exception type and map that to 401 (or whatever you want):

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/samples/ProblemDetails.Sample/Program.cs#L70-L71
