### ISSUE TITLE
Use your middleware for MVC with Views

### ISSUE THREAD

**Issue by shuegelm** [khellang/Middleware#117]
Is there a way, i dont see, to use your middleware in connection with Views? I am already using your great package for my asp.net core 3.1 API project. But now I am using ASP.NET Identity with Identity Server to instantiate an Identity Provider. Currently all exceptions are forwarded to a basic Action called `Error` in the `HomeController` of my project. So I guess its possible to also catch the exceptions from the service with your middleware and transform them into details. But currently I am lacking of imagination to see the best practice her. Could you please give me some hints?

**Comment by khellang** [comment]
I'm not really sure how this fits with views. The RFC is specific about JSON and XML, which doesn't seem to fit with views. AFAIC, this middleware is for APIs only. You're probably better of using some error views in MVC for your use case 😊

**Comment by shuegelm** [comment]
Thanks, i guess too.
