### ISSUE TITLE
Feature Request: Logging on error

### ISSUE THREAD

**Issue by gingjonesy** [khellang/Middleware#119]
Is there a way to include or have an option to log the exception that caused the problem details in the first place. This way you could optionally set it to log exception via your logging component (nlog, log4net) instead of having a global exception handler or middleware to do this part.

Not sure if this is out of scope for what this middleware is intended to do.

**Comment by khellang** [comment]
Indeed. In fact, there's already some logging going on here:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsMiddleware.cs#L103-L106

It should be logged as error with the key `UnhandledException` and say something like

> An unhandled exception has occurred while executing the request.

...and include the exception information. Are you not seeing this in your app?

You can control the logging by setting the `ShouldLogUnhandledException` option. By default it's set to only log exceptions resulting in a 5xx error code:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsOptionsSetup.cs#L19-L22

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/src/ProblemDetails/ProblemDetailsOptionsSetup.cs#L56-L60

Hopefully this will solve your request 😄

**Comment by gingjonesy** [comment]
Yea I'm not currently seeing any logging coming through. I've configured to use nlog and its working currently when I have a global filter to handle the logging outside of this middleware. NLog just gets setup in the Program file, is there anything I maybe need added to the startup for this to work with ProblemDetails? 

This is what i have in my filter. Theres not alot to it, the only difference i see is i set ILogger in here to logFactory.CreateLogger(typeof(ExceptionLoggingFilter));

`public class ExceptionLoggingFilter : IExceptionFilter
    {
        private readonly ILogger _logger;

        public ExceptionLoggingFilter(ILoggerFactory logFactory)
        {
            _logger = logFactory.CreateLogger(typeof(ExceptionLoggingFilter));
        }

        public void OnException(ExceptionContext context)
        {
            var message = $"{context.Exception.Message} : {context.Exception.InnerException?.Message} : {context.Exception.StackTrace}";
            _logger.LogError(context.Exception, message.Substring(0, 1499));
        }
    }`

**Comment by khellang** [comment]
> is there anything I maybe need added to the startup for this to work with ProblemDetails?

There shouldn't be anything other than setting up ASP.NET Core logging. It just uses the regular `ILogger` injection from ASP.NET.

**Comment by khellang** [comment]
Hey @gingjonesy! 👋

Did you figure out the logging? I just tested it with the sample app in this repo and it's definitely logging by default.

If you'd like some help debugging this, you could push a minimal sample to GitHub, so I can take a look 😊

**Comment by toralux** [comment]
@khellang I still miss possibility to do my own logging. I prefer logging with Serilog as I can log structured objects in the way I want. I could have used "OnBeforeWriteDetails() if it also returned the Exception, but now it doesn't.

**Comment by khellang** [comment]
@toralux What kind of logging are you looking for? You haven't hooked up Serilog to the built-in logging in ASP.NET Core? I'm not sure a general purpose exception logging feature should be included in this middleware. IMO, it's better suited outside in a separate middleware, like Serilog.Exceptions or just the request logging middleware for Serilog.
