### ISSUE TITLE
Blazor WASM Sample

### ISSUE THREAD

**Issue by Jimmys20** [khellang/Middleware#122]
Hello, could you please provide a basic sample project of using the problem details middleware in a Blazor wasm asp.net core hosted application? How would you handle the response deserialization on the Client? I know this out of scope for this library which is only responsible for creating the error responses on the server side. Nevertheless, I would really like to have your opinion on this matter or maybe a few tips.

I have set up a new project based on the webassemply template with only minor changes so far. Basically hooking up the middleware on the Server project Startup.
https://github.com/Jimmys20/Blazor.ProblemDetails

**Comment by khellang** [comment]
Hey @Jimmys20! 👋🏻 

I've actuallyl never tried Blazor before, so you kinda nerd sniped me on this one 😉 

I think you should be able to do something like this; https://github.com/Jimmys20/Blazor.ProblemDetails/pull/1.

AFAIK, there's no central error handler in Blazor WASM, so you'll have to add `try`/`catch` blocks manually, but it seems to work.

**Comment by Jimmys20** [comment]
Hello, I replaced the HttpClientExtensions with a DelegatingHandler, seems to be working fine. It might be worth including these classes in a small nuget package to make it easier to consume ProblemDetails responses. Maybe I'll give it a try.

https://github.com/Jimmys20/Blazor.ProblemDetails/commit/fadd543491e2b62b32462d3d7364b5d65ebb7d26

**Comment by khellang** [comment]
Nice. Yeah, if only there was a global place to catch those exceptions and update a piece of UI, that would be great 😅 A polished NuGet package for something like this would be cool 😎 I've thought about doing the same for a React component on NPM for the longest time... 😅
