### ISSUE TITLE
Transform MVC responses containing ModelStateDictionary (or SerializableError)

### ISSUE THREAD

**Issue by khellang** [khellang/Middleware#125]
Hmm... This one should definitely be fixed 🤔

> * AddProblemDetailsConventions: BadRequest(ModelState) does NOT produce a problem detail response

_Originally posted by @khellang in https://github.com/khellang/Middleware/issues/124#issuecomment-807564459_

**Comment by m-knet** [comment]
Good job @khellang! Just now I have noticing the lack of this feature
