### ISSUE TITLE
Add options for MVC parts

### ISSUE THREAD

**Issue by khellang** [khellang/Middleware#126]
I'd also like to start adding some knobs to the MVC part of the library, like the default status code for validation problems 😊

_Originally posted by @khellang in https://github.com/khellang/Middleware/issues/124#issuecomment-807579619_

**Comment by christianacca** [comment]
Any idea of an eta?

**Comment by khellang** [comment]
Pushed v5.3.0 with support for `return BadRequest(ModelState)` (#125) and a new option, `ValidationProblemStatusCode`, that you can set to override the default status code for validation errors 😃

**Comment by christianacca** [comment]
Wow, thank you!

The only difference between the conventions in the same sample app and what
you (now) get out of the box from the middleware is the value that gets
assigned to the Type property of a problem detail response. The sample app
used the built-in MVC client mapping for this.

Really the main reason for that at the time was to keep the middleware and
what is produced by ASP.Net Core model validation the same. Now that your
middleware can change what ASP.Net core model validation outputs to be the
same as the middleware, I think there is no strong reason to keep this last
convention in the sample application.

I'll update the sample app to just use AddProblemDetailsConventions and
remove all the conventions I had going on.

C
