### ISSUE TITLE
Shameless plug? New package to send problem details to MS application insights

### ISSUE THREAD

**Issue by christianacca** [khellang/Middleware#128]
Kristian, I've created a new package that enriches application insights with details extracted from a ProblemDetail created by the ProblemDetails.Middleware: https://github.com/christianacca/ApplicationInsights.ProblemDetails

Maybe it would be useful to put a link to this from the README of this repo to raise the awareness?

**Comment by khellang** [comment]
Nice 😎 Yeah, I'd gladly take a pull request 👌
