### ISSUE TITLE
Swashbuckle output different from demo

### ISSUE THREAD

**Issue by EdoVanAsseldonk** [khellang/Middleware#132]
Dear Kristian,

I've noticed that in the demo at https://problem-details-demo.azurewebsites.net/swagger/index.html#/ApiMvc/ApiMvc_ErrorDetails the error has a description:

![image](https://user-images.githubusercontent.com/3816410/114298428-a81b0300-9ab6-11eb-91b4-ddb03c604b82.png)

However, if I create a new ASP.Net 5.0 Web API, then I don't get that description:

![image](https://user-images.githubusercontent.com/3816410/114298451-c41ea480-9ab6-11eb-9d88-8a952d6d96dd.png)

Everything else is the same as you can see. I've looked to the example source code, but couldn't figure out what causes this. Do you have any idea?

The steps to reproduce:
Create a new Web API in Visual Studio 2019, version 16.10.0 Preview 1.0
Add `services.AddProblemDetails(ConfigureProblemDetails);` to `Startup.ConfigureServices(...)`
Add the following method to Startup:

```
private void ConfigureProblemDetails(ProblemDetailsOptions o)
{
    o.ValidationProblemStatusCode = StatusCodes.Status400BadRequest;
}
```

Add `app.UseProblemDetails();` as first line to `Startup.Configure(...)`

Change the Get method in the WeaterForecastController to

```
[HttpGet]
[ProducesResponseType(StatusCodes.Status422UnprocessableEntity)]
public IEnumerable<WeatherForecast> Get()
{
   ModelState.AddModelError("someProperty", "This property failed validation.");

   var validation = new ValidationProblemDetails(ModelState)
   {
      Status = StatusCodes.Status422UnprocessableEntity
   };

   throw new ProblemDetailsException(validation);
}
```

**Comment by khellang** [comment]
Hi @EdoVanAsseldonk! 👋

Did you also call `AddProblemDetailsConventions` on your MVC builder? It adds a few things to make MVC play nicer with the middleware. It might be the reason why it's behaving differently?

https://github.com/khellang/Middleware/blob/0a4f07a629c222a56e0e9f83f99df1c825c4a72f/samples/ProblemDetails.Sample/Program.cs#L45-L46

**Comment by khellang** [comment]
At that point, you could also simplify the code like this:

https://github.com/khellang/Middleware/blob/0a4f07a629c222a56e0e9f83f99df1c825c4a72f/test/ProblemDetails.Tests/ProblemDetailsMiddlewareTests.cs#L598-L603

And if you want 422 instead of 400, you can just call the `UnprocessableEntity` method instead:

https://github.com/khellang/Middleware/blob/0a4f07a629c222a56e0e9f83f99df1c825c4a72f/test/ProblemDetails.Tests/ProblemDetailsMiddlewareTests.cs#L611-L615

**Comment by EdoVanAsseldonk** [comment]
`.AddProblemDetailsConventions()` didn't make any difference. I'll clone the demo source and try to figure out the difference with my code.

**Comment by angularsen** [comment]
I just stumbled on this trying to figure out how to document ProblemDetails in our swagger docs. Didn't know `AddProblemDetailsConventions` even existed until now. 

### Suggestion
Let 500 status codes default to the `ProblemDetails` schema in swagger, similar to 400 bad request.

### Reasoning
After some experimentation, it seems `[ProducesResponseType]` without specifying error type renders a response body schema for status code 400 but not for 500.
```cs
[ProducesResponseType(StatusCodes.Status400BadRequest)]
[ProducesResponseType(StatusCodes.Status500InternalServerError)]
public class MyController : ControllerBase {}
```

![image](https://user-images.githubusercontent.com/787816/150995635-d441b672-b9b0-4e0b-b106-aef7c191984f.png)

If `typeof(ProblemDetails)` is specified, the response body schema is declared for both status codes.
```cs
[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
public class MyController : ControllerBase {}
```

![image](https://user-images.githubusercontent.com/787816/150995947-9f92fd85-857b-4641-8204-f50593c87277.png)

`AddProblemDetailsConventions` makes no difference, it seems.

In practice all our 500 status codes also return a `ProblemDetails` with this middleware. 
I believe this is the most typical case, so it could be a minor improvement to default 500 status codes to the `ProblemDetails` schema, similar to 400 bad request.

**Comment by khellang** [comment]
This is some magic deep inside MVC, so I'll have to dig a bit deeper into how it works.

Accoding to [this](https://github.com/dotnet/aspnetcore/blob/07d728b517005ec655925d83bd7b66538145be81/src/Mvc/Mvc.Core/src/ApplicationModels/ApiBehaviorApplicationModelProvider.cs#L44-L46), MVC sets the default error response type to `typeof(void)` if `SuppressMapClientErrors` is set to `true`, which `AddProblemDetailsConventions` does:
 
https://github.com/khellang/Middleware/blob/eb7f59cb5aaff0727466622af6230db12703a32f/src/ProblemDetails/Mvc/ProblemDetailsApiBehaviorOptionsSetup.cs#L10-L11

So I'd expected your 400 status code to have no example value in this case 🤔 

At the same time, there seems to be some special handling of client errors [here](https://github.com/dotnet/aspnetcore/blob/9b736b467a87494c28cf8a3d77cd4e6f9ffd2e86/src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs#L166-L172). Honestly I'm not sure where to start here 😅

**Comment by angularsen** [comment]
Thanks for the details. I don't have a grasp on the built-in client details stuff, so I can't help there. This is not a big problem for us really, just a minor suggestion if you are interested in digging into it. I won't pursue this myself, I mostly found it peculiar. 😄

**Comment by angularsen** [comment]
One more thing, I can't seem to understand whether we need the `AddProblemDetailsConventions` or not just by looking at the xmldoc or source. Everything has been working as expected without it, what am I potentially missing out on? Any known scenarios?

https://github.com/khellang/Middleware/blob/42597d3a43c1bbc1beeff4ab272432df03f0be08/src/ProblemDetails/Mvc/MvcBuilderExtensions.cs#L20

**Comment by angularsen** [comment]
This was the closest explanation I could find.
https://github.com/khellang/Middleware/issues/149#issuecomment-945195002

So it seems it is mostly about transforming results like `return BadRequest(ModelState)` into problem details then?

**Comment by khellang** [comment]
It does three things:

1. It swaps MVC's built-in `ProblemDetailsFactory` to use the middleware's configuration instead. This will give you more consistent errors, no matter where they are produced. I.e. from MVC's invalid state filter etc.
2. It turns off MVC's built-in client error mapping, which also gives you more consistent error responses
3. It tries to [set the produced error response type on API controllers](https://github.com/khellang/Middleware/blob/eb7f59cb5aaff0727466622af6230db12703a32f/src/ProblemDetails/Mvc/ProblemDetailsApplicationModelProvider.cs#L15-L21), but apparently that isn't working too well 😅

**Comment by angularsen** [comment]
This would be very useful to have in the README I think.
Sorry for being slow, but when exactly does nr 1 and 2 occur? I have no idea when invalid state filter or built-in client error mapping is used.

**Comment by khellang** [comment]
Oh, and it adds [a filter](https://github.com/khellang/Middleware/blob/eb7f59cb5aaff0727466622af6230db12703a32f/src/ProblemDetails/Mvc/ProblemDetailsResultFilter.cs) that makes returning pre-baked `ProblemDetails` instances from controllers a bit more consistent, by calling the middleware hooks 😃

> Sorry for being slow, but when exactly does nr 1 and 2 occur? I have no idea when invalid state filter or built-in client error mapping is used.

See the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-6.0#validation-failure-error-response). Basically if you have an API controller that returns back a 4xx status code (with no body) or model validation fails, MVC will use the `ProblemDetailsFactory` to create an instance of `ProblemDetails` and return it back, bypassing this middleware completely. So in order to make the responses consistent between MVC and the middleware, I've provided the `AddProblemDetailsConventions` method to smooth things out a bit 😃
