### ISSUE TITLE
Question: Is it possible to strong name the assembly?

### ISSUE THREAD

**Issue by ElectricVampire** [khellang/Middleware#134]
@khellang 

I created similar library and was using it from some time but yesterday when I came across this one library and all the features it offers I wanted to use this one.
Unfortunately there is a rule in our build pipeline which throws error when it encounters library which is not strong named.

Is it possible to strong name assembly in this nuget?

**Comment by khellang** [comment]
> Is it possible to strong name assembly in this nuget?

It's certainly possible, but not something I have time to dig into right now. I'd take a pull request if you're up for it. Otherwise, you could use [StrongNamer](https://github.com/dsplaisted/strongnamer) to do it for you.

Just out of curiosity, can I ask why you have such a restriction/limitation in your build pipeline?

**Comment by ElectricVampire** [comment]
To be honest, I am not sure, its a firm wide pipeline maintained by another team. Earlier we used to deploy our code in GAC, where it make sense to have signed dlls, I think its a legacy validation rule in pipeline.
I'll first check with that team if they can relax this rule, otherwise I'll send a PR.

**Comment by khellang** [comment]
Yeah, I remember doing it for Scrutor a while back (see [this commit](https://github.com/khellang/Scrutor/commit/4cca435db248aa59e63f8e5caea1d337fea40ced) and [this commit](https://github.com/khellang/Scrutor/commit/2751901992c43741a9fa0fe41c05bb797a92e9db)), but I'm pretty swamped with other work right now 😅

**Comment by ElectricVampire** [comment]
I'll create an PR

**Comment by khellang** [comment]
Added strong-name signing and pushed v6.0.0 to NuGet 😄
