### ISSUE TITLE
Localization integration

### ISSUE THREAD

**Issue by markbangert** [khellang/Middleware#136]
First of all a big thank you for maintaining this package. I am a big fan :)

At the moment, however, I struggle, with the integration of string localization with the middleware. Ideally I would like to use [IStringLocalizer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.istringlocalizer?view=dotnet-plat-ext-5.0) to provide localized error messages. At the moment though we are using the middleware to intercept all errors and transform them in standardized ProblemDetails objects for our clients (including some enrichment with other properties). While I could throw the errors with localized strings, this would mean I would have to inject IStringLocalizer everywhere I throw an error. Is it possible somehow to incorporate this into the configuration of the AddProblemDetails middleware? Right now I have the following approach in my startup.cs

```
            services.AddProblemDetails(options =>
            {
                options.Map<BackendException>((ctx, ex) =>
                {
                    var provider = services.BuildServiceProvider();
                    var localizerFactory = provider.GetService<IStringLocalizerFactory>();
                    var localizer = new StringLocalizer<MyResources>(localizerFactory);

                    return new BackendProblemDetails
                    {
                        Title = string.Format(localizer[ex.ErrorIdentifier], ex.Parameters),
                        Type = ex.GetType().ToString(),
                        Status = (int)ex.StatusCode,
                        ...
                    };
                });
            });
```

However, the string localizer will not be injected with the desired culture :(

Any ideas would be greatly apprecieated. Thanks / Mark

**Comment by khellang** [comment]
Hey @markbangert! 👋

Could you use `ctx.RequestServices` to get the localizer/factory instead? That should be properly set up in a request context ☺️

**Comment by markbangert** [comment]
@khellang thank you for your answer. It turns out that the problem is, that the services that are provided though both `ctx.RequestServices` and `services.BuildServiceProvider()` do not inherit the correct culture settings. However, setting

```
var rqf = ctx.Request.HttpContext.Features.Get<IRequestCultureFeature>();
var requestCulture = rqf.RequestCulture.Culture; 
            
CultureInfo.CurrentUICulture = requestCulture;
```

before getting the localizationServices will fix this.

**Comment by khellang** [comment]
I'm glad you figured out a solution 😁

 Isn't there an official middleware for setting the correct request culture? Maybe you just need to place that middleware in front of (before) the ProblemDetails middleware? 🤔

**Comment by markbangert** [comment]
I do use the [official middleware for localization](https://docs.microsoft.com/de-de/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#implement-a-strategy-to-select-the-languageculture-for-each-request) which works just fine at other parts of the code (e.g. within controllers) but not when setting up the PorblemDetails mapping in startup.

**Comment by khellang** [comment]
Hmm, that's weird 🤔

 The mapping runs in the request pipeline (where `UseProblemDetails` is called), so it requires `UseRequestLocalization` to be called before `UseProblemDetails` in order for the localization to be properly set up.

 I can see if I'm able to reproduce it when back behind a keyboard (currently on vacation 😅)
