### ISSUE TITLE
Incorrect Content-Type on Problem responses if using ProducesAttribute and NotFoundObjectResult

### ISSUE THREAD

**Issue by TU-OB-GW** [khellang/Middleware#137]
Steps to reproduce:

1. In aspnetcore 3.1 web api project, add Hellang.Middleware.ProblemDetails nuget reference, wire up services and middleware in Startup.cs
2. Annotate an Api Controller with ProducesAttribute and multiple content types, e.g. `[Produces("application/hal+json", "application/problem+json")]`
3. Add logic to a Controller action such that a `NotFoundObjectResult` with a string value is returned.  e.g. via the ControllerBase.NotFound(object value) helper method
4. Start the web app and send a request to the action to trigger the NotFoundResult.  Inspect response Content-Type header, it will be the first content type passed to the ProducesAttribute rather than application/problem+json

I think the issue may be due to [line 96](https://github.com/khellang/Middleware/blob/e89e45aafa7f71f6474b37c24134b785551edf09/src/ProblemDetails/Mvc/ProblemDetailsResultFilter.cs#L96) of `ProblemDetailsResultFilter`, which assigns ProblemDetailsOptions.ContentTypes to an ObjectResult.ContentTypes whereas it probably should be copying the contents of the collection across to a new MediaTypeCollection instance instead (because ProducesAttribute calls ObjectResult.ContentTypes.Clear())

If I pin it down while coding a workaround I'll be happy to submit a PR to fix, thanks

**Comment by khellang** [comment]
Hi @TU-OB-GW! 👋

I'm currently on vacation and won't be able to look at this for some time, but if you figure out why, I'd gladly take a PR to fix it! 👍

**Comment by TU-OB-GW** [comment]
Seems I assessed this incorrectly, it's not the combination of StatusCodeResult, ProducesAttribute and ProblemDetailsResultFilter that is the cause, but rather it's using an ObjectResult with a detail string e.g. NotFound("The resource x was not found")

I've removed the example project for now, will replace it tomorrow and hopefully get a PR raised later in the week when I've tested my workaround properly.

Have a good vacation Kristian!

**Comment by TU-OB-GW** [comment]
Am exploring the simple workaround of setting the ProducesAttribute.Order property to -2001 to force it to execute before ProblemDetailsResultFilter.  Not entirely sure this will work for all scenarios though.

**Comment by TU-OB-GW** [comment]
Workaround seems to work just fine with problems generated via Controller code or invalid model state. @khellang what's your thoughts on changing ProblemDetailsResultFilter.Order from -2000 to 1 so that it executes after a ProducesAttribute with a default order of 0?

**Comment by khellang** [comment]
Ah, it's an ordering issue? Yeah, I don't think I have a problem with adjust it. The problem with order properties is always what values you should use 😅

**Comment by TU-OB-GW** [comment]
Re-ordering has certainly made it go away for now but I'm also going to tweak ProblemDetailsOptions.ContentTypes to be an IList<MediaTypeHeaderValue> rather than MediaTypeCollection, and add a GetContentTypes method that returns a new MediaTypeCollection each time to be assigned to ObjectResult.  i.e. cover up the indecent exposure ;)
