### ISSUE TITLE
[question] throw exception from custom middleware in asp.net with problemdetails for the  problemdetailsmiddleware

### ISSUE THREAD

**Issue by christopherpross** [khellang/Middleware#142]
Hey,
I haven't found an example for that, is that possible?
I want to throw an exception from a custom middleware with a problemdetails / validationsproblem object so that the problemdetailsmiddleware can catch it and can generate a response.
The documentation is confusing.

all the best,
Christopher

**Comment by khellang** [comment]
> I haven't found an example for that, is that possible?

Yes, it's possible. See the following snippet from the sample:

https://github.com/khellang/Middleware/blob/f440483694f4a107f6c1a8a04204e06490e0bf05/samples/ProblemDetails.Sample/Program.cs#L140-L145

The sample code is from an MVC controller, but there shouldn't be any difference between them.

**Comment by christopherpross** [comment]
@khellang  hey,
thank you, for the answer, yeah, but the ProblemDetailsException is marked as Obsiolete. I thought that I shouldn't use that.

**Comment by khellang** [comment]
Where is `ProblemDetailsException` marked as obsolete? https://github.com/khellang/Middleware/blob/f440483694f4a107f6c1a8a04204e06490e0bf05/src/ProblemDetails/ProblemDetailsException.cs

**Comment by christopherpross** [comment]
sorry I was only confused, I have confound https://raw.githubusercontent.com/khellang/Middleware/master/src/ProblemDetails/ProblemDetailsException.cs with https://raw.githubusercontent.com/khellang/Middleware/master/src/ProblemDetails/ExceptionProblemDetails.cs

Closing this now, resolved, thank you!
