### ISSUE TITLE
[question] no support for 500 errors?

### ISSUE THREAD

**Issue by nicostubi** [khellang/Middleware#143]
Hello Kristian,

Any reasons for not supporting errors 500? 

Best Regards,
Nicolas

**Comment by nicostubi** [comment]
Hi,

I mean, I found a lot of resources pretending that adding this lines are enough:

```
services.AddProblemDetails(); 
app.UseProblemDetails();
```

Like this one for example: https://www.infoworld.com/article/3584786/how-to-use-the-problemdetails-middleware-in-aspnet-core.html

Is it really enough?

When doing so, I still have the default .net formatting for errors 500.

Best Regards,
Nicolas

**Comment by khellang** [comment]
Hi @nicostubi! 👋🏻 

> Any reasons for not supporting errors 500?

Nope, no reason. Of course there's support for 500 errors 😆 Out of the box, it's just a plain `ProblemDetails` response with exception details only added in `Development` environment.

> I found a lot of resources pretending that adding this lines are enough. Is it really enough?

No need to pretend. Check out [the sample](https://github.com/khellang/Middleware/blob/master/samples/ProblemDetails.Sample/Program.cs) an example configuration and how it can be used.

> When doing so, I still have the default .net formatting for errors 500.

BTW, there's no default .NET formatting. Unless you have some middleware in your pipeline that catches exceptions and formats them. Something's telling me your pipeline isn't set up properly, but without any code (preferably a repro project) or other description of your setup, it's really hard to give you any pointers 😅

**Comment by nicostubi** [comment]
Hi @khellang 

Thanks for your answer. 

Here is a repro project.

As you will see, the endpoint `/WeatherForecast `is returning a system.Exception not formatted with the `ProblemDetails`.

When I enter a wrong URL, the `ProblemDetails `is there:

![image](https://user-images.githubusercontent.com/47106274/132173816-556e4363-bf27-4958-884b-f913dd1af14e.png)

Best Regards,
Nicolas

[WebApplication4.zip](https://github.com/khellang/Middleware/files/7113926/WebApplication4.zip)

**Comment by khellang** [comment]
I see you have `UseDeveloperExceptionPage` in development. That will probably catch the exception and render an exception page instead 😅

**Comment by nicostubi** [comment]
Yes, indeed. Thanks. No I am having the same problem in my "real" project. So I will compare both.

Thanks!

BR
Nicolas
