### ISSUE TITLE
ProblemDetailsException with inner exception

### ISSUE THREAD

**Issue by fernetowac** [khellang/Middleware#144]
Hi,
is there any reason why ProblemDetailsException doesn't have constructor with innerException parameter? It derives from Exception and therefore it should contain such constructor as stated in docs of Exception class.

In my particular case, I'd like to rethrow catched exception then to be wrapped by ProblemDetailsException and not loose the stacktrace of original catched exception.

Thanks

**Comment by khellang** [comment]
Hi @fernetowac! 👋

Nope, no reason. It just hasn't been needed before. I'd gladly take a PR for it 🙂

**Comment by khellang** [comment]
Closed by #145
