### ISSUE TITLE
ProblemDetails: exception details always included regardless of configuration

### ISSUE THREAD

**Issue by spaasis** [khellang/Middleware#147]
Hi,

ProblemDetails 6.2.0

In startup.cs I have defined:
```
            services.AddProblemDetails(options => {
                options.IncludeExceptionDetails = (ctx, ex) => false; //disabled completely for verifying the bug
                options.MapToStatusCode<NotImplementedException>(StatusCodes.Status501NotImplemented);
                    options.MapToStatusCode<HttpRequestException>(StatusCodes.Status503ServiceUnavailable);
                    options.MapToStatusCode<Exception>(StatusCodes.Status500InternalServerError);
                })
                .AddControllers()
                .AddProblemDetailsConventions()
                .AddJsonOptions(x => x.JsonSerializerOptions.IgnoreNullValues = true);
```

But even with the exception details disabled completely, the inner exception and stack trace are included in the response when performing e.g. a 400 Bad Request .

I can't seem to find any other conflicting configuration for this in my code.

Any ideas?

**Comment by khellang** [comment]
Hi @spaasis! 👋🏻 

Hmm. That sounds very weird. This code clearly checks `IncludeExceptionsDetails` before adding them to the response:

https://github.com/khellang/Middleware/blob/7a2a6f220121cf3421bfc1ad770532f1aa1d1d23/src/ProblemDetails/ProblemDetailsFactory.cs#L60-L73

Can you paste en example response?

**Comment by khellang** [comment]
I just tried running [the sample](https://github.com/khellang/Middleware/samples/ProblemDetails.Sample) and hitting both `/middleware/error` and `/mvc/error` with `IncludeExceptionDetails` returning both `true` and `false` and I can't reproduce what you're seeing.

**Comment by spaasis** [comment]
@khellang Yup, I'm a bit baffled as well.

Here's a sample response:

```
{
  "error": {
    "code": "",
    "message": "The query specified in the URI is not valid. Could not find a property named 'doesnotexist' on type 'API.Models.ObservationSiteMunicipality'.",
    "details": [],
    "innererror": {
      "message": "Could not find a property named 'doesnotexist' on type 'API.Models.ObservationSiteMunicipality'.",
      "type": "Microsoft.OData.ODataException",
      "stacktrace": "   at Microsoft.OData.UriParser.SelectPathSegmentTokenBinder.ConvertNonTypeTokenToSegment(PathSegmentToken tokenIn, IEdmModel model, IEdmStructuredType edmType, ODataUriResolver resolver, BindingState state)\r\n   at Microsoft.OData.UriParser.SelectExpandBinder.ProcessSelectTokenPath(PathSegmentToken tokenIn)\r\n   at Microsoft.OData.UriParser.SelectExpandBinder.GenerateSelectItem(SelectTermToken tokenIn)\r\n   at Microsoft.OData.UriParser.SelectExpandBinder.Bind(ExpandToken expandToken, SelectToken selectToken)\r\n   at Microsoft.OData.UriParser.SelectExpandSemanticBinder.Bind(ODataPathInfo odataPathInfo, ExpandToken expandToken, SelectToken selectToken, ODataUriParserConfiguration configuration, BindingState state)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpandImplementation(String select, String expand, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()\r\n   at Microsoft.AspNet.OData.Query.SelectExpandQueryOption.get_SelectExpandClause()\r\n   at Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuting(ActionExecutingContext context)"
    }
  }
}
```

**Comment by khellang** [comment]
Yeah, I can tell you right away that that response hasn't been generated by this middleware. Nothing matches the expected schema :)

**Comment by khellang** [comment]
The schema looks remarkably similar to some of Microsoft APIs' error responses, like [this](https://powerapps.microsoft.com/en-us/blog/web-api-innererror-property-will-be-removed/).

**Comment by spaasis** [comment]
D'oh, of course. Now to figure out why the 400 is not mapped correctly with this configuration.. Thanks for the assist!

**Comment by spaasis** [comment]
Amusing. Once again OData is doing it's own thing...

Even though I set `options.MapToStatusCode<ODataException>(StatusCodes.Status400BadRequest);`  the ODataExceptions fly straight through and use their own error reporting...

https://github.com/OData/WebApi/issues/1898

**Comment by khellang** [comment]
Lovely. Another reason to stay away from OData 😅

**Comment by spaasis** [comment]
If only we could...

**Comment by spaasis** [comment]
But for the historical record, the custom `EnableQuery` attribute from the linked issue, combined with this excellent middleware, provides the wanted result

**Comment by hexagonite** [comment]
If you are using the AspNetCoreOData package, the solution I've found is to combine [a custom ODataSerializer](https://github.com/OData/AspNetCoreOData/blob/main/docs/customize_odataerror.md) with an error-handling middleware. This way you can control the response body and thus clear the stack trace from it. Some exceptions will be caught in your middleware, and some in the serializer (because some exceptions are being handled automatically within the private methods of this package and no middleware will help you).
