### ISSUE TITLE
Call `AddProblemDetailsConventions` directly on `IServiceCollection`

### ISSUE THREAD

**Issue by lonix1** [khellang/Middleware#150]
To use `AddProblemDetailsConventions()` we must do this:
````cs
services                                // returns IServiceCollection
  .AddControllers()                     // returns IMvcBuilder        <---- here's the problem
  .AddProblemDetailsConventions();
````

In some environments, that `IMvcBuilder` isn't available or easy to access. For example when using a [modular](https://github.com/henkmollema/StartupModules) startup, or Orchard Core. Other [libraries](https://github.com/FluentValidation/FluentValidation/issues/1726) also had this problem, it's quite common.

All that extension method does is call [`IMvcBuilder.IServiceCollection`](https://github.com/khellang/Middleware/blob/1b445f121e0ce23a0573266335cc4d83d20401c4/src/ProblemDetails/Mvc/MvcBuilderExtensions.cs#L23-L30). Would it be possible to add an **overload** (not a breaking change!) to accept that directly:
````cs
public static IServiceCollection AddProblemDetailsConventions(this IServiceCollection services)
{
  //identical to other overload
}
````

We could call it like so:
````cs
services.AddProblemDetailsConventions();
````

I would patch this myself but I never figured out the github PR thing. :) It would be a great improvement and add major flexibility when configuring app startup.

I hope this can be considered. **Thank you!**

**Comment by lonix1** [comment]
You mean my half-assed attempt at pretending I know how to use github properly? "You're welcome". If it breaks I'm sorry! :smile:

**Comment by lonix1** [comment]
If there's a pre-release build somewhere, let me know if you want me to beta test it.

**Comment by khellang** [comment]
Hey @lonix1! Sorry it took some time, but ended up pushing v6.3.0 to NuGet today 😄
