### ISSUE TITLE
Can it be used with .net 6?

### ISSUE THREAD

**Issue by developer9969** [khellang/Middleware#153]
Hi 
Thanks for this nuget. I am new to this and looks exactly what I am looking for.

Does it work with .net 6?

Thanks

**Comment by khellang** [comment]
Hello @developer9969! 👋🏻 

> Does it work with .net 6?

Yes, I'm not aware of any issues running on .NET 6. Give it a try and give me a shout if you encounter any 😄

**Comment by developer9969** [comment]
Hi 
Thank you for replying, what you did is great.

- I would like to log the same info that you display when iIncludeExceptionDetails= Dev but I am struggling to see how you do it.
- Instance is null
- Details only contains minimal info, whilst in postman I get the full stackframes-ExceptionDetails etc..
- How do I extract these data easily so that I can log it ?

```
  public static IServiceCollection AddProblemDetailsOptions(
            this IServiceCollection services,
            IWebHostEnvironment currentEnvironment, 
            global::Serilog.ILogger logger)
        {
            services.AddProblemDetails(options =>
            {
                options.IncludeExceptionDetails = (ctx, env) => currentEnvironment.IsDevelopment() || currentEnvironment.IsStaging();

                options.Map<MyCustomException>(exception => new ProductCustomDetails
                {
                    Title = exception.Title,
                    Detail = exception.Detail,
                    Status = StatusCodes.Status500InternalServerError,
                    Type = exception.Type,
                    Instance = exception.Instance,
                    AdditionalInfo = exception.AdditionalInfo
                });

                options.MapToStatusCode<NotImplementedException>(StatusCodes.Status501NotImplemented);
                options.MapToStatusCode<HttpRequestException>(StatusCodes.Status503ServiceUnavailable);
                options.MapToStatusCode<Exception>(StatusCodes.Status500InternalServerError);

               //log stuff now!!
                options.OnBeforeWriteDetails = (ctx, problemDetails) =>
                {
                    problemDetails.Extensions["traceId"] = ctx.TraceIdentifier;
                    logger.Error(problemDetails.Detail);     
                    logger.Error(problemDetails.Extensions.FirstOrDefault().Value.ToString());     
                    logger.Error(problemDetails.Instance);   //WHY IS THIS NULL? 
                };
            });

            return services;
        }
```

May thanks for your time and this nuget

**Comment by khellang** [comment]
Hmm. I'm not sure what's going on here. `OnBeforeWriteDetails` is called right before the response is written to the client, so it should contain all the details at that point. Would you be able to produce a Minimal, Reproducible Example that I could take a look at? It's hard to tell based on your setup code what's producing the `ProblemDetails` instance.

**Comment by developer9969** [comment]
Hi
Really appreciate your help. I might be missing the obvious. See attached app (vs2022 rc)


[WebApiSampleProblemDetails.zip](https://github.com/khellang/Middleware/files/7480965/WebApiSampleProblemDetails.zip)

Issues:
OnBeforeWriteDetails: 

1. When throwing a simple exception(throw new NotImplementedException();) I would like to log the raw message but I cannot seem to get it out of extensions.
2. Instance is not populated.

**Instructions**

1. Launch the app in swagger 
2. execute "/WeatherForecast"
3. Will Throw "NotImplementedException" 
4. When logging instance will be null
5. How can I log the entire exceptionDetails 

**Validation**

1. Launch the app in swagger 
2. execute "/WeatherForecast/{City}" 
3. Type "aaa" in city  I  have hardcoded it to trigger validation
4. How can I log the entire exceptionDetails 

Many thanks again for your time

**Comment by khellang** [comment]
> 1. I would like to log the raw message but I cannot seem to get it out of extensions.

Yeah, it's a bit hard to log the exception message from `OnBeforeWriteDetails` because it doesn't know about the exception. The problem response could've been produced by a status code as well, so the exception might not be there. There's a callback you can hook into that is specific to the exception side of error handling, namely `ShouldLogUnhandledException`, or you could simply say that exceptions should be rethrown by calling `Rethrow<Exception>()` and have your own error logging middleware downstream (before) the problem details middleware. At that point, you can just wrap the call to `next` with a `try/catch` and log whaterever you want.

> 2\. Instance is not populated.

That's right. When mapping an exception to a standard `StatusCodeProblemDetails`, [`instance` won't be set](https://github.com/khellang/Middleware/blob/f8d62f70913cdaf2fc53cd840d01ce24be1d3b92/src/ProblemDetails/StatusCodeProblemDetails.cs#L35-L40). I'm not sure what to populate it with. If you have any suggestions (that are also in line with RFC 7807), I'm happy to hear it.

> Also what is not clear to me if you get an HttpStatus 500 for example when you make an httpcall I was expecting this to be converted to a problem details automatically inside the middleware? Am I wrong? I am getting the raw exception and not the problemdetails one. Missing something obvious here?

It depends. If you make an upstream HTTP call (say, from a controller), you need to make sure to either throw, i.e. call `EnsureSuccessStatusCode`, or return something that sets the status code to 5xx. There's no automatic handling of upstream HTTP errors in the middleware. It's basically just doing error handling by catching exceptions and mapping non-success status codes to problem responses.

**Comment by developer9969** [comment]
Hi first of all thanks for your time in replying

> I would like to log the raw message but I cannot seem to get it out of extensions

Logging as you know is the most important part as you know as this is what us developers we will be looking at to fix the issue and the 2 Exceptions and logging go very much together.
I am already using "ShouldLogUnhandledException
ShouldLogUnhandledException=(ctx,problemDetails)=>problemDetails.Status is =>500;
Are u saying that here 

1. I should rethrow the exception 
2. Write it in my own exception middleware? Hooked before yours?


> Instance not populated

 I might be wrong here but  I have looked at quite a few problemdetails samples and I thought that the instance was always populated with the endpoint you are calling . I.E if _"https://github.com/khellang/Middleware/issues/153"_ wouldnt HttpContext.GetEndpoint() do the trick?

> Throwing errors so that they are caught by your middleware

I will use "EnsureSuccessStatusCode" to throw any failed upstream Http call

Sorry 2 more questions 

1. Will you consider extending your middleware to handle logging to?
2. I have tried to have your middleware running in code against my api to see what is doing but it does not build for me with a couple classes I.E ExceptionDetails is inaccessible to protection level.

It would be nice to see what is doing if I can run it locally myself.. any suggestions?

Again thank you for your time

**Comment by khellang** [comment]
> Are u saying that here

No, I'm saying you could either do your logging here (where you have access to the exception) OR you could go the rethrow route (there's built-in support for rethrowing certain exceptions).

> I might be wrong here but I have looked at quite a few problemdetails samples and I thought that the instance was always populated with the endpoint you are calling . I.E if _"[whatever/customers/1](https://whatever/customers/1)"_ wouldnt HttpContext.GetEndpoint() do the trick?

This is not something the middleware does by default, but you can certainly include that mapping yourself. I've tried to not be too opinionated on the default mapping, as the RFC itself is pretty vague on the `instance` property:

> A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced.

To me, it's not clear that this means the URL of the request, but I can see how people interpret it that way. Anyway, I'm not sure I'm willing to include this in the default mapping (yet).

> Will you consider extending your middleware to handle logging to?

I do include some basic logging (as you've noticed `ShouldLogUnhandledException`), but anything more than that I think users will have to add themselves. When it comes to logging, it get into opinion-land very quickly, so I think it's better to leave it up the users. The middleware already provides the rethrow functionality to be able to pass the exception further down the pipeline. People already use this for logging, APM etc.

> I have tried to have your middleware running in code against my api to see what is doing but it does not build for me with a couple classes I.E ExceptionDetails is inaccessible to protection level.

Are you saying the solution won't build? The latest CI built successfully, so it should be able to build. The solution uses a few AspNetCore classes that are internal, maybe you need to run a `git submodule -q update --init` to fetch those bits before building?

**Comment by developer9969** [comment]
Thanks for replying and all makes sense.

> The middleware already provides the rethrow functionality to be able to pass the exception further down the pipeline. 

Is there an example anywhere about it so that I can implement it too?

**Comment by developer9969** [comment]
thank you for all your replies.

**Comment by christianacca** [comment]
@khellang, in .net 6 it looks like `DeveloperExceptionPageMiddleware` is ALWAYS added as one of the first middleware in the pipeline as explained [here](https://andrewlock.net/exploring-dotnet-6-part-4-building-a-middleware-pipeline-with-webapplication/#the-empty-pipeline). Whereas in .net 5 (and below), I just wouldn't include it as `UseProblemDetails` is  preferable even for a local dev environment.

Can you think of any likely conflict with having both `DeveloperExceptionPageMiddleware` (at the start) AND `ProblemDetailsMiddleware` in the pipeline?

**Comment by khellang** [comment]
@christianacca [Indeed](https://github.com/dotnet/aspnetcore/blob/94ffe0356177368d73f98021da53456fc658fcd4/src/DefaultBuilder/src/WebApplicationBuilder.cs#L245-L248). I don't think it would be a problem. It only catches exceptions from downstream middleware, and as the `ProblemDetailsMiddleware` would be _after_ the `DeveloperExceptionPageMiddleware`, exceptions will be caught in `ProblemDetailsMiddleware` and never reach the `DeveloperExceptionPageMiddleware`. Even if you have re-throwing configured, the `ProblemDetailsMiddleware` will write to the response, which stops `DeveloperExceptionPageMiddleware` [from writing to the response](https://github.com/dotnet/aspnetcore/blob/94ffe0356177368d73f98021da53456fc658fcd4/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L100-L104).

**Comment by christianacca** [comment]
Cool. thanks for the clarification
