### ISSUE TITLE
The nuget package for ProblemDetails has been updated to 6.4.0, but there is no matching release on this repository

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [khellang/Middleware#161]
Hi! 
I just noticed that https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails is now in version 6.4.0

But there isn't a tag or a release 6.4.0 in this repository yet.

Can I have more information about this? I find this strange.

**Comment by khellang** [comment]
It's not _that_ strange. I just forgot to create the release. It should be pretty easy to figure out the change log by looking at the commits. The 6.4.0 release is basically a single commit changing a single method from internal to public (see https://github.com/khellang/Middleware/pull/159). I'll make sure I push the tag and create a release when I have time 😅

**Comment by Alexandre-Nourissier** [comment]
No problem, it's just that there is no proof that this version only includes the changelog declared. I wanted to be sure that this new version wasn't fraudulent.

Thank you very much for your hard work!

**Comment by khellang** [comment]
> it's just that there is no proof that this version only includes the changelog declared

Sure, but a release on GitHub is not proof of this.

I could add whatever code I wanted to the NuGet package, push it to the gallery, but never push the code anywhere. It would then be easy to create a GitHub release and come up with some fake (or real) bug fixes and improvements that the release contains. It doesn't prove anything though.

There's also other ways an attacker could publish a new version of a package alongside a new release on GitHub. I've tried to make it as hard as possible by using complex unique passwords and enabling MFA everywhere, but there's always a chance.

At the end of the day, you have to look at the git commit SHA embedded in the package, rebuild the package on your own machine and verify that the files match. In that case you can be sure that the code in the package is exactly the same as it says 😅

I'm not sure the process is producing 100% deterministic builds, but that could be fixed if this is a big concern.

**Comment by khellang** [comment]
Added the v6.4.0 release to GitHub; https://github.com/khellang/Middleware/releases/tag/v6.4.0
