### ISSUE TITLE
Links to httpstatuses domain sent elsewhere

### ISSUE THREAD

**Issue by lonix1** [khellang/Middleware#167]
This library replaces the reference for status codes to links to `https://httpstatuses.com/xxx`, which is quite helpful.

Has anyone noticed that lately that those links go to a different domain? The above domain was probably sold.

For example, a link to `https://httpstatuses.com/401` goes to `https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-401-status-code/`.

If that domain belongs to you @khellang then I've no problem with it, it's your right as the library owner after all. Just curious. :smiley:

**Comment by khellang** [comment]
> Has anyone noticed that lately that those links go to a different domain? The above domain was probably sold.

Hmm, that's not good. Looks like it's still providing the relevant information (at least it's not redirecting to some port site 😅), but we should definitely look at some other resource. Any suggestions?

**Comment by lonix1** [comment]
LOL - it feels so.... "Wordpressy" - a plugin you've used for years is sold and redirects to porn.

There's many alternatives, but they're very "commercial". We should use one similar to the old one, i.e. a clean "reference" site.

The best is probably MDN, which also links to each RFC.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200

**Comment by khellang** [comment]
Ah, I was thinking about MDN, but didn't know they had a URL based on the status code as an integer. That could probably work. I would be cool if they had some shorter, culture-neutral URLs though.

**Comment by khellang** [comment]
Looks like https://developer.mozilla.org/docs/Web/HTTP/Status/200 will redirect you to your preferred culture :)

**Comment by blogcraft** [comment]
Why not use datatracker.ietf.org/doc/html/rfc7231 URLs to point to the correct status code doc? 

I have a Gist that does that: [URL Docs](https://gist.github.com/blogcraft/810c560c65ccdc87e8dc7690e3427828)

**Comment by lonix1** [comment]
That is a good option, but MDN is more friendly and more helpful in most cases. And it links to the RFC if you need to do more digging. Most people want a TL;DR.

**Comment by khellang** [comment]
Yeah, and some status codes are not part of 7231, like 206, 308, 401, 412, 422 etc. MVC has worked around this by linking to [RFC7235](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Shared/ProblemDetailsDefaults.cs#L19-L23) and [RFC4918](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Shared/ProblemDetailsDefaults.cs#L55-L59), but it would be nice if there was just a single site that had a TL;DR for all status codes with links to explore more details.

**Comment by khellang** [comment]
Maybe I should create my own site that aggregates them all, like the old httpstatuses.com, with a tiny ad at the bottom for some extra income 😜

**Comment by lonix1** [comment]
A nice idea, and then when it gets big enough, sell it to a porn site.

**Comment by blogcraft** [comment]
![image](https://user-images.githubusercontent.com/5615323/161784529-2557696b-f2c4-4200-911a-1e671bddd3de.png)

Lol it remembers me of this.

**Comment by khellang** [comment]
Closed with #173. Thank @collinstevens! 😘

**Comment by khellang** [comment]
Pushed to NuGet.org as v6.4.2 😁

**Comment by lonix1** [comment]
Thanks!

Too bad for that company - I hope we are not putting them out of business. :yum:
