### ISSUE TITLE
Google token validation with local authentication

### ISSUE THREAD

**Issue by javahemans** [khellang/Middleware#3]
Hey 

First of all I should mention that you're library is very good and makes it easier to validate Google token. As I am new to `.net core` a question raised in my mind.

I am currently having a `.net core` **React** application that is configured with local authentication with JWT. 

```c#
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme) 
                .AddJwtBearer(options => {
                                       options.TokenValidationParameters = new TokenValidationParameters
                                       {
                                           ValidateIssuer = true,
                                           ValidateAudience = true,
                                           ValidateLifetime = true,
                                           ValidateIssuerSigningKey = true,
                                           ValidIssuer = "yourdomain.com",
                                           ValidAudience = "yourdomain.com",
                                           IssuerSigningKey = new SymmetricSecurityKey(
                                               Encoding.UTF8.GetBytes("secret key"))
                                       };
                                   });


```

Now I want to add Google token validation and I was wondering to ask, will I be able to use your NuGet package and have my local authentication flow? 

If I can would that be something like this? 

```c#
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme) 
                .AddJwtBearer(options => {
                                       options.TokenValidationParameters = new TokenValidationParameters
                                       {
                                           ValidateIssuer = true,
                                           ValidateAudience = true,
                                           ValidateLifetime = true,
                                           ValidateIssuerSigningKey = true,
                                           ValidIssuer = "yourdomain.com",
                                           ValidAudience = "yourdomain.com",
                                           IssuerSigningKey = new SymmetricSecurityKey(
                                               Encoding.UTF8.GetBytes("secret key"))
                                       };
                                   })
                .AddJwtBearer(x => x.UseGoogle(
                     clientId: "<google-client-id>",
                     hostedDomain: "<optional-g-suite-domain>"));
```

Cheers

**Comment by khellang** [comment]
> If I can would that be something like this?

Hmm. I've never actually done this before, but I'm assuming, since you're asking, that it didn't work?

It's probably because both calls to `AddJwtBearer` will use the same scheme, `JwtBearerDefaults.AuthenticationScheme`.

I think you might have to add each `JwtBearer` handler with a custom scheme, i.e.

```csharp
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme + ".Local", options => { /* ... */ });
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme + ".Google", options => { /* ... */ });
```

You probably also want to remove the default scheme parameter when calling `AddAuthentication`, since you now have two different schemes.

See [this StackOverflow answer for more details](https://stackoverflow.com/a/49706390/682105).

**Comment by nazarkryp** [comment]
@khellang do you have some tutorial or sample with full startup.cs config?

**Comment by khellang** [comment]
Not really. I'm on vacation right now, so I'm unable to set one up for you. I guess you need to find a tutorial for [local JWT Bearer auth](https://jonhilton.net/2017/10/11/secure-your-asp.net-core-2.0-api-part-1---issuing-a-jwt/) and combine the answer with the StackOverflow answer linked above and this library. If you have any specific questions ot issues, I might be able to answer them, though.

**Comment by khellang** [comment]
Hey @javahemans and @nazarkryp! Did you get anywhere with this? Can I close the issue?

**Comment by nazarkryp** [comment]
Hello. I haven’t been trying it a lot. But i have got a point. I have no more questions

**Comment by javahemans** [comment]
yup, got it working
