### ISSUE TITLE
How does this work in conjunction with Problem Details being the default return for 4xx errors in Core 2.2?

### ISSUE THREAD

**Issue by VictorioBerra** [khellang/Middleware#39]
https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2?view=aspnetcore-2.2#problem-details-support

I am currently encountering an issue where I am throwing my own custom exception and catching it in my own custom middleware. The annoying problem right now is since updating from 2.1 to 2.2 , by using the default MVC stuff like `return NotFound()` returns problemdetails but throwing MyCustomException does not. This is what led me here to your library.

My worry is, if I choose to use this library, I will diverge from the default handling of the ProblemDetails stuff. **I want to lean into the MVC default implementation of ProbleDetails. Not a different take on it, or a custom implementation.** I am hoping this library does that and can help me.

**Comment by khellang** [comment]
> My worry is, if I choose to use this library, I will diverge from the default handling of the ProblemDetails stuff.

The middleware uses the MVC formatting pipeline, which means it uses the exact same serialization settings as MVC. It also uses MVC's `ProblemDetails` type, so it'll be compatible, for sure.

> I want to lean into the MVC default implementation of ProbleDetails. Not a different take on it, or a custom implementation.

This middleware handles much more than what MVC does, though. It's really designed to be an exception handling middleware (that also happens to convert non-success status codes to problem details responses, like MVC 2.2 does).

> I am hoping this library does that and can help me.

All in all, you can safely use this middleware to handle what MVC doesn't. It should be fine :smile:
