### ISSUE TITLE
map my custom exception to ExceptionProblemDetails

### ISSUE THREAD

**Issue by namnik** [khellang/Middleware#45]
Hi dears,
at first, I read your sample in the GitHub, run it, and fine worked.

but in my real application, I have a Custom exception class that used in the domain layer.  this class derived from System.Exception. and has multiple extra property(errorCode, errorMsg, StatusCode).

now I want to map my exception class to ExceptionProblemDetails class when configure the problem detail in ConfigureServices() in the startup.

I know  also you map with this code:

`            options.Map<MyCustomException>(ex => new ExceptionProblemDetails(ex, (int)ex.HttpStatusCode));
`

can I map my properties to the property of  the problem detail class before write response by the ProblemDetailsMiddleware. for example(mapping):

new ProblemDetails()
            {
                Title = myCustomException.Code.ToString(),
                Detail = myCustomException.Message,
                Status = (int?)myCustomException.HttpStatusCode
            })

thanks.

**Comment by khellang** [comment]
Uhm, sure, just return the code you just wrote above inside your mapping lambda?

**Comment by namnik** [comment]
no, I want to return full object(code, status, messsge). I know the above code is wrong!

**Comment by namnik** [comment]
before create this issue I wrote your above code and return correct data.
but with this code ,Serilog don't log my exception, because of didn't  throw ExceptionProblemDetails() in the above code. then I thought my code(same your code) was wrong.
did you idea for this challenge(Serilog)?

**Comment by khellang** [comment]
Have you hooked up Serilog to the ASP.NET Core logging pipeline?

**Comment by namnik** [comment]
yes of course, before mapping my exception to ProblemDetailException, Seriog logs my exception! but now just log my info logs!

**Comment by khellang** [comment]
What is the status code of the mapped details object? We only log server-side errors, i.e. status code 500+

**Comment by namnik** [comment]
<code>
options.Map<MyCustomException>(ex => new ProblemDetails()
{
Title = ex.Code.ToString(),
Detail = ex.Message,
Status = HttpStatusCode.BadRequest
}));

</code>
above code is my final mapping.

**Comment by khellang** [comment]
...and does that work?

**Comment by namnik** [comment]
above code return object correctly, but didn't log throwed  exceptions of type 'MyCustomException'.

**Comment by khellang** [comment]
> but didn't log throwed exceptions of type 'MyCustomException'.

Right. That's because the status code is 400, and we only log 500+ error codes by default. I pushed a new version to NuGet that allows you to set

https://github.com/khellang/Middleware/blob/10d508e1071a86dd59360b0f15760aca0e7d43ba/src/ProblemDetails/ProblemDetailsOptions.cs#L43

when configuring the middleware. It will allow you to tweak when the middleware will log an exception as "unhandled", as people seem to want different things here.

Example:

```csharp
services.AddProblemDetails(options =>
{
    options.ShouldLogUnhandledException = (e, d) =>
    {
       	return e is MyCustomException || (d.Status.HasValue && d.Status.Value >= 500);
    }
});
```

**Comment by namnik** [comment]
thanks a lot. I will test it tomorrow!

**Comment by khellang** [comment]
Great! Let me know if it works so we can close this issue 👌
