### ISSUE TITLE
Pass HttpContext to Map() and MapStatusCode() as optional parameters

### ISSUE THREAD

**Issue by ts46235** [khellang/Middleware#46]
There are things in the request that I"d like to base the exception on so it would be handy if that was passed in whenever an exception should be created. One thing is the RequestServices to get a hold of scoped dependencies since we have no way to do that right now.

The parameter could be nullable/optional to not break backwards compatibility. 

Thanks for your contribution

**Comment by ngRevan** [comment]
It would also make sense to pass the HttpContext to OnBeforeWriteDetails.

**Comment by khellang** [comment]
Good points both! I'm thinking I'd just do a breaking change and bump the major version for this 👌
