### ISSUE TITLE
expose httpContextAccessor in options

### ISSUE THREAD

**Issue by namnik** [khellang/Middleware#47]
Hi dear;
I want to pass the path of current request to Instance property of Problem Details.
for example:

services.AddProblemDetails(options =>
{
options.Map<MyCustomException>(ex => new ProblemDetails()
{
Title = ex.Code.ToString(),
Detail = ex.Message,
Status = (int?)ex.HttpStatusCode,
Instance= httpContextAccessor.HttpContext.Request.Path
}));

Can I access to httpContextAccessor?

**Comment by khellang** [comment]
This seems like a duplicate of https://github.com/khellang/Middleware/issues/46. I'll try to get this fixed today.

**Comment by namnik** [comment]
Thanks for your contribution
