### ISSUE TITLE
 IncludeExceptionDetails prints path "C:\Users\khe1\..."

### ISSUE THREAD

**Issue by CleytonGoncalves** [khellang/Middleware#48]
Hi there! First of all I would like to thank you for this amazing package :)

Not sure if this is expected behavior, but with IncludeExceptionDetails, there's a few of: `"C:\\Users\\khe1\\Code\\Middleware\\src\\ProblemDetails\\ProblemDetailsMiddleware.cs"`

Full response (redacted sensitive info with `[...]`):
<pre>
{
    "errors": [
        {
            "message": "External component has thrown an exception.",
            "type": "System.Runtime.InteropServices.ExternalException",
            "raw": " [...]  at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context) in <b>C:\\Users\\khe1\\Code\\Middleware\\src\\ProblemDetails\\ProblemDetailsMiddleware.cs</b>:line 52",
            "stackFrames": [
                {"filePath":"C:\\Users\\MyUser\\[...]\\Controllers\\ErrorController.cs","fileName":"ErrorController.cs","function":"[...].ErrorController.GetException()","line":50,"preContextLine":44,"preContextCode":["        public IActionResult Get500() => StatusCode(500,","            new ExceptionProblemDetails(new ExternalException(\"Internal Exception Message\"), 500));","","        /// <summary> Produz erro 500 - Internal Server Error </summary>","        [HttpGet(\"Exception\")]","        [ProducesResponseType(StatusCodes.Status500InternalServerError)]"],"contextCode":["        public IActionResult GetException() => throw new ExternalException();"],"postContextCode":["    }","}"]},
                {"filePath":null,"fileName":null,"function":"lambda_method(Closure , object , object[] )","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, object[] parameters)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
                {"filePath":null,"fileName":null,"function":"Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)","line":null,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null},
<b>
                {"filePath":"C:\\Users\\khe1\\Code\\Middleware\\src\\ProblemDetails\\ProblemDetailsMiddleware.cs"</b>,"fileName":"ProblemDetailsMiddleware.cs","function":"Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)","line":52,"preContextLine":null,"preContextCode":null,"contextCode":null,"postContextCode":null}
            ]
        }
    ],
    "type": "https://httpstatuses.com/500",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "External component has thrown an exception.",
    "traceId": "0HLKUGQA6V1TJ:00000003"
}
</pre>

**Comment by khellang** [comment]
Hmm. That is indeed weird. I wonder if a debug build has made its way to NuGet? Or if somehow PDBs have been included in the package? 🤔

**Comment by khellang** [comment]
I tried pushing a new version, v3.0.1, to NuGet. Do you mind testing it to see if you still get the same details?

**Comment by CleytonGoncalves** [comment]
Tested it, looks alright to me!
