### ISSUE TITLE
Refresh Token 

### ISSUE THREAD

**Issue by mitulsuthar** [khellang/Middleware#50]
Hi, 
I have been using your library for validating token issued by Google Authentication and it is been working great. However, the token seems to expire pretty soon, probably one hour. I am using Aspnetcore API with Angular. 

How should I refresh the token? Is this supposed to be done at the client side or server side? Any pointers in the right direction would help. 

Thanks,

**Comment by khellang** [comment]
Hey! The server-side JWT authentication only validates a Google `id_token` (which is a JWT), not an `access_token`.

If you want to get a new `access_token` (and `id_token`) using a refresh token, you have to handle that on the client side.

If you're using the Google libraries to authenticate, they usually do the refreshing for you. If not, that's kinda up to you to handle.

**Comment by mitulsuthar** [comment]
Thanks for clarifying. I will do some research on this. 

> Hey! The server-side JWT authentication only validates a Google id_token (which is a JWT), not an access_token.

So access_token is not really a JWT token. Am I correct?

**Comment by khellang** [comment]
> So `access_token` is not really a JWT token. Am I correct?

Yes, I think that's correct. It's [documented as](https://developers.google.com/identity/protocols/OpenIDConnect):

> A token that can be sent to a Google API.

While `id_token` is documented as:

> A [JWT](http://openid.net/specs/draft-jones-json-web-token-07.html) that contains identity information about the user that is digitally signed by Google.
