### ISSUE TITLE
WithExceptionDetails feature request

### ISSUE THREAD

**Issue by MarcoGix** [khellang/Middleware#51]
Hi there!
Thanks for this helpful package! 
I have integrated it into my project but there are some behaviour that are not exactly as expected for me.

I was looking for something that you did in branch aspnetcore 2.2: 
 
	ex.WithExceptionDetails(details)
	
but more generic, for all kind of problem details, not only ExceptionProblemDetails.

The point is, if I want to map the exception to a custom class, I will not have the details added to that..

        private MvcProblemDetails GetDetails(HttpContext context, Exception error)
        {
            var statusCode = context.Response.StatusCode;

            if (error == null)
            {
                return Options.MapStatusCode(context, statusCode);
            }

            var result = GetProblemDetails(context, error);

            // We don't want to leak exception details unless it's configured,
            // even if the user mapped the exception into ExceptionProblemDetails.
            if (result is ExceptionProblemDetails ex)  // <------------------------------ Here
            {
                if (Options.IncludeExceptionDetails(context))
                {
                    try
                    {
                        var details = DetailsProvider.GetDetails(ex.Error);
                        return ex.WithExceptionDetails(details);
                    }
                    catch (Exception e)
                    {
                        // Failed to get exception details for the specific exception.
                        // Fall back to generic status code problem details below.
                        Logger.ProblemDetailsMiddlewareException(e);
                    }
                }

                return Options.MapStatusCode(context, ex.Status ?? statusCode);
            }

            return result;
        }

In practice, when I use a custom ProblemDetailsException, there is no Stack Trace added to that..

	private MvcProblemDetails GetProblemDetails(HttpContext context, Exception error)
	{
		if (error is ProblemDetailsException problem)
		{
			// The user has already provided a valid problem details object.
			return problem.Details;
		}

		if (Options.TryMapProblemDetails(context, error, out var result))
		{
			// The user has set up a mapping for the specific exception type.
			return result;
		}

		// Fall back to the generic exception problem details.
		return new ExceptionProblemDetails(error);
	}
	
Do you accept PR on aspnetcore Branch?
Or is it possible to have a similar feature, extended for all problem details, also on main branch?
	
Thanks!

**Comment by khellang** [comment]
I've pushed a new version v5.0.0-beta.1 to NuGet.org that should hopefully address this problem. It would be awesome if you had time to check it out 😄🙏
