### ISSUE TITLE
log just Message Exception

### ISSUE THREAD

**Issue by namnik** [khellang/Middleware#52]
Hi Dear,
about problem Detail Middle-ware;
when throwed Unhandled exception, logs all stack trace of the exception in my log file.
I want to log just the message of my exception. can I do that?

thanks

**Comment by khellang** [comment]
> I want to log just the message of my exception. can I do that?

I'm not really sure. There's no way of customizing this in the middleware. It's just using the ASP.NET Core logger and pipes through the exception. You might have to provide your own custom logger if you want to avoid outputting the stack trace.

**Comment by khellang** [comment]
I'm closing this as I don't think there's anything I can do about this in the middleware.
