### ISSUE TITLE
Problem details middleware to aggressive with exception mapping

### ISSUE THREAD

**Issue by jcasale** [khellang/Middleware#53]
When mapping exceptions and configuring additional problem details using an approach similar to the following:

```cs
problemOptions.Map<MyException>(ex => new ExceptionProblemDetails(ex, StatusCodes.Status400BadRequest)
{
    Detail = ex.Message,
    Instance = "http://example.com/foo/..."
});
```

the aggressive handling by the middleware removes the opportunity to at least provide the contextual data, not just the exception details. The default handler then writes a bare status code problem details.

https://github.com/khellang/Middleware/blob/4e38c0762aee9145a8523c77994bf293bbd65777/src/ProblemDetails/ProblemDetailsMiddleware.cs#L112-L132

It would be far more convenient to facilitate this in order to remove the boilerplate necessary to catch the exceptions and rethrow/return a problem details object at the call site.

**Comment by khellang** [comment]
Are you saying you're losing data because the exception is being mapped to a `DeveloperProblemDetails`? 🤔 

Yeah, that problem has come up before. It's essentially the same as https://github.com/khellang/Middleware/issues/51. I'll have to fix this by mutating the returned result to provide the exception details.

**Comment by jcasale** [comment]
Hi, I am losing the base properties in the `Microsoft.AspNetCore.Mvc.ProblemDetails` implementation when `ProblemDetailsOptions.IncludeExceptionDetails` is false. The conditional at L116 jumps to L131 and the implementation there ignores the base instance of `ProblemDetails` which I populate in the call to `Map<MyException>`.

If the call to `MapStatusCode` had an overload which also passed the exception instance, we could have access to it when we configure problem details in `AddProblemDetails`.

That would be a non breaking enhancement:wink:

**Comment by jcasale** [comment]
I have looked at this in more detail, if I convert the exception in `Map` directly to the `ProblemDetails` instance I need, the conditional at [L114](https://github.com/khellang/Middleware/blob/4e38c0762aee9145a8523c77994bf293bbd65777/src/ProblemDetails/ProblemDetailsMiddleware.cs#L114) skips the exception all together.

I understand your desire to prevent leakage, but you can't in all cases since the caller can create their own `ProblemDetails` with the exception data and swallow the exception. I think that decision should be left to the caller as this assurance is not absolute given the reduction in flexibility.

How do you feel about the following logic which more closely follows the expectation of *always* revealing the exception when configured, but offers the flexibility of allowing the caller to construct the result when not in developer mode:
```cs
private MvcProblemDetails GetDetails(HttpContext context, Exception error)
{
    var statusCode = context.Response.StatusCode;

    if (error == null)
    {
        return Options.MapStatusCode(context, statusCode);
    }

    var result = GetProblemDetails(context, error);

    if (Options.IncludeExceptionDetails(context))
    {
        try
        {
            var problem = new ExceptionProblemDetails(error, result.Status ?? statusCode);
            var details = DetailsProvider.GetDetails(error);

            return new DeveloperProblemDetails(problem, details);
        }
        catch (Exception e)
        {
            // Failed to get exception details for the specific exception.
            Logger.ProblemDetailsMiddlewareException(e);
        }
    }

    return result;
}

private MvcProblemDetails GetProblemDetails(HttpContext context, Exception error)
{
    if (error is ProblemDetailsException problem)
    {
        // The user has already provided a valid problem details object.
        return problem.Details;
    }

    if (Options.TryMapProblemDetails(context, error, out var result))
    {
        // The user has set up a mapping for the specific exception type.
        return result;
    }

    // Fall back to a generic status code problem details.
    return Options.MapStatusCode(context, context.Response.StatusCode);
}
```

**Comment by khellang** [comment]
I'll have a look at this together with https://github.com/khellang/Middleware/issues/51 to see if I can come up with some logic that will be flexible enough to cover all cases.

**Comment by khellang** [comment]
I've pushed a new version v5.0.0-beta.1 to NuGet.org that should hopefully address this problem. It would be awesome if you had time to check it out 😄🙏

**Comment by jcasale** [comment]
Unfortunately I do not have a project with the package any longer. :worried:
