### ISSUE TITLE
"No output formatter was found for content type '' to write the response."

### ISSUE THREAD

**Issue by VictorioBerra** [khellang/Middleware#54]
`WriteProblemDetails` never updates the `context.Response.ContentType` so if you use `.AddMvcOptions(options => options ReturnHttpNotAcceptable = true ... ` like me then you end up with the error above and the caller gets a 406.

Maybe if we are responding with an obvious `MvcProblemDetails` we should be setting the response content?

**Comment by VictorioBerra** [comment]
Hmm maybe `ReturnHttpNotAcceptable` kicks in before this can set the type?? https://github.com/aspnet/Mvc/pull/8512

**Comment by khellang** [comment]
Hmm, yeah that might be it. I'm relying on MVC's formatting pipeline to write the response, so I would expect it to be set 🤔

**Comment by VictorioBerra** [comment]
I am not sure why something is "wiping" the content type. I spent a good while trying to get a super simple reproduction app but I am struggling.

**Comment by VictorioBerra** [comment]
It seems to be related to this project actually https://github.com/damienbod/WebAPIContrib.Core/tree/master/src/WebApiContrib.Core.Formatter.Csv

If i set my "Accept" header to `text/csv` then I get the error in my title here. Still trying to dig and investigate into why. I think im nearing the end of my knowledge about the internals of the MVC formatters and media type stuff. So any help is appreciated. I have no idea how it sets the response content type headers and selects the formatters, etc.

**Comment by VictorioBerra** [comment]
Actually maybe not.

This gives me a 406 `sdsdfs/dsasdsa` while this does not `sdsdfsdsasdsa`

Simply removing the slash lands me with a 500 and `application/problem+json` as expected.

**Comment by VictorioBerra** [comment]
@khellang Full reproduction https://github.com/VictorioBerra/khelland-middleware-mvc-bug-54

Just do a GET to api/values/Explode which thgrows a simple Exception. Make sure you set an Accept header of type "text/csv" to see the console error.

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:4300/api/values/explode
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.8473ms 307
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:4301/api/values/explode
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'example.Controllers.ValuesController.Explode (example)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Route matched with {action = "Explode", controller = "Values"}. Executing controller action with signature System.Threading.Tasks.Task`1[System.Int32] Explode(System.Threading.CancellationToken) on controller example.Controllers.ValuesController (example).
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method example.Controllers.ValuesController.Explode (example) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action example.Controllers.ValuesController.Explode (example) in 34.5595ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'example.Controllers.ValuesController.Explode (example)'
fail: Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: Kaboom!
   at example.Controllers.ValuesController.Explode(CancellationToken cancellationToken) in C:\Users\toryb\Desktop\khelland-middleware-mvc-bug-54\src\example\Controllers\ValuesController.cs:line 48
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[1]
      No output formatter was found for content type '' to write the response.
warn: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      No output formatter was found for content type '' to write the response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 64.6094ms 406
```

**Comment by khellang** [comment]
> I am not sure why something is "wiping" the content type.

The `ProblemDetailsMiddleware` is wiping all headers if an exception occurs to ensure a "clean" response. The built-in error handling middleware does the same. But that shouldn't really matter as the `ObjectResult` being returned has `ContentType` set and the formatting pipeline should respect those.

> I think im nearing the end of my knowledge about the internals of the MVC formatters and media type stuff. So any help is appreciated. I have no idea how it sets the response content type headers and selects the formatters, etc.

To be honest, I think the behavior you're seeing here is expected. By setting `ReturnHttpNotAcceptable` to `true` and sending `Accept: text/csv`, you've explicitly said (as a client) that you *only* accept `text/csv` and told MVC to only format a response if it's able to match the client's `Accept` header.

Because of the error in the controller, you're hitting the `ProblemDetailsMiddleware`, which is only able to produce a `application/problem+json` (or `+xml`) response. That means MVC is no longer able to match the client's *only* acceptable media type, `test/csv`, and MVC ends up returning a 406 response.

The only solution to this that I can see, is to also include `application/problem+json` in your `Accept` header. Or turn `ReturnHttpNotAcceptable` back off.

Now, part of the reason for your confusion is probably the warning being logged:

> No output formatter was found for content type '' to write the response.

I'd say this is a bug in MVC. The error only outputs the `Response.ContentType` and doesn't include the MVC result's `ContentTypes`, which is why it's being shown as blank, even though both `application/problem+json` and `application/problem+xml` was considered. I'll file an issue in the AspNetCore repo (and maybe send a PR) to get this fixed.

Just to confirm, could you turn the logging level (in `appsettings.Development.json`) up to `Debug` to make sure we get the additional details logged in the `DefaultOutputFormatterSelector`?

I'm specifically looking for the following message:

> "Attempting to select an output formatter based on Accept header '{AcceptHeader}' and explicitly specified content types '{ExplicitContentTypes}'. The content types in the accept header must be a subset of the explicitly set content types."
---

Side note: Why are you explicitly adding these content types to the output formatters?

https://github.com/VictorioBerra/khelland-middleware-mvc-bug-54/blob/c8751babc1683ca02405d2e219feee55f10a7946/src/example/Startup.cs#L72-L79

The JSON output formatter should support all media types with a `+json` structured syntax suffix, so it shouldn't be necessary.

**Comment by khellang** [comment]
Filed #11173.

**Comment by VictorioBerra** [comment]
@khellang Thanks a lot this is very helpful. At what point in the pipeline here does MVC compare the orig request accept header to the ObjectResult response content type? That is to say, when does it compare `Accept: text/csv` to `Content-Type: application/problem+json`

> Side note: Why are you explicitly adding these content types to the output formatters?

I was trying different stuff from a [dotnet api template I use called Boxed](https://github.com/Dotnet-Boxed/Templates/blob/master/Source/Content/ApiTemplate/Source/ApiTemplate/MvcCoreBuilderExtensions.cs#L66-L94).

Full debug output you requested via the sample app:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:4301/api/values/explode
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      2 candidate(s) found for the request path '/api/values/explode'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'example.Controllers.ValuesController.Explode (example)' with route pattern 'api/Values/explode' is valid for the request path '/api/values/explode'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'example.Controllers.ValuesController.Get (example)' with route pattern 'api/Values/{id}' is valid for the request path '/api/values/explode'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'example.Controllers.ValuesController.Explode (example)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'example.Controllers.ValuesController.Explode (example)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Explode", controller = "Values"}. Executing action example.Controllers.ValuesController.Explode (example)
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of authorization filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of resource filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of exception filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[22]
      Attempting to bind parameter 'cancellationToken' of type 'System.Threading.CancellationToken' ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[23]
      Done attempting to bind parameter 'cancellationToken' of type 'System.Threading.CancellationToken'.
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[26]
      Attempting to validate the bound parameter 'cancellationToken' of type 'System.Threading.CancellationToken' ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[27]
      Done attempting to validate the bound parameter 'cancellationToken' of type 'System.Threading.CancellationToken'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method example.Controllers.ValuesController.Explode (example) with arguments (System.Threading.CancellationToken) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action example.Controllers.ValuesController.Explode (example) in 83.4133ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'example.Controllers.ValuesController.Explode (example)'
fail: Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: Kaboom!
   at example.Controllers.ValuesController.Explode(CancellationToken cancellationToken) in C:\Users\tory.berra\Desktop\khelland-middleware-mvc-bug-54\src\example\Controllers\ValuesController.cs:line 48
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[11]
      List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, WebApiContrib.Core.Formatter.Csv.CsvOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[7]
      Attempting to select an output formatter based on Accept header 'text/csv' and explicitly specified content types 'application/problem+json, application/problem+xml'. The content types in the accept header must be a subset of the explicitly set content types.
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[5]
      Could not find an output formatter based on content negotiation. Accepted types were (text/csv)
warn: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[1]
      No output formatter was found for content type '' to write the response.
warn: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      No output formatter was found for content type '' to write the response.
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HLNG3DKJKE6G" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 134.1653ms 406
```

**Comment by khellang** [comment]
> At what point in the pipeline here does MVC compare the orig request accept header to the ObjectResult response content type? That is to say, when does it compare `Accept: text/csv` to `Content-Type: application/problem+json`

Where it says

> Attempting to select an output formatter based on Accept header 'text/csv' and explicitly specified content types 'application/problem+json, application/problem+xml'. The content types in the accept header must be a subset of the explicitly set content types.

It then (correctly) says

> Could not find an output formatter based on content negotiation. Accepted types were (text/csv)

Which in turn ends up with the following unhelpful warning:

> No output formatter was found for content type '' to write the response.

**Comment by khellang** [comment]
I don't think there's much more I can do here. I'm pretty sure this is the correct (or at least expected) behavior. If anything needs to change, it'll have to be in MVC. I'll send a PR to MVC ASAP to close https://github.com/aspnet/AspNetCore/issues/11173.
