### ISSUE TITLE
Throw ProblemDetailsException in client when server responds with application/problem+json

### ISSUE THREAD

**Issue by mabead** [khellang/Middleware#55]
I use your library to automatically return a `application/problem+json` responses from my services when something goes wrong. The next thing that I would like to do is to be able to call this service (the server) from another remote piece of code (the client) using an HttpClient + AutoRest generated client. So when the server responds with a `application/problem+json` response, I would like my the call made on the client to throw a `ProblemDetailsException`. 

Is this something that you have in your library or something that you intend to implement? I quickly looked in the code but I couldn't find anything.

I think that this is typically done using a `DelegatingHandler` that can be provided to AutoRest.

**Comment by VictorioBerra** [comment]
This isn't really the responsibility of this library but yes you could add your own outgoing middleware and then check the response and throw your own exception.

**Comment by khellang** [comment]
> Is this something that you have in your library or something that you intend to implement?

It's not something I have in the library and not something I'm planning to include as I'd like it to remain server-side only, but I've implemented something like this many times.

> I think that this is typically done using a `DelegatingHandler` that can be provided to AutoRest.

Yes, using a `DelegatingHandler` with `HttpClient` would be the way to go. If you get a response back and the `Content-Type` is `application/problem+json`, you'd deserialize the response and throw a `ProblemDetailsException` on the client.

**Comment by mabead** [comment]
Ok, thanks @khellang . For reference, here's how I did it:

```csharp
    public class ProblemDetailsDelegatingHandler: DelegatingHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            HttpResponseMessage response = null;
            try
            {
                response = await base.SendAsync(request, cancellationToken);

                var mediaType = response.Content.Headers.ContentType.MediaType;

                if (string.Equals(mediaType, "application/problem+json", StringComparison.OrdinalIgnoreCase))
                {
                    var bodyString = await response.Content.ReadAsStringAsync();
                    var problemDetails = JsonConvert.DeserializeObject<ProblemDetails>(bodyString);

                    throw new ProblemDetailsException(problemDetails);
                }

                return response;
            }
            catch
            {
                // Safely dispose the response as explained here: https://stackoverflow.com/a/49922102/2679757
                response?.Dispose();
                throw;
            }
        }
    }
```
