### ISSUE TITLE
Why "add back" headers? Response.Clear() does not remove headers.

### ISSUE THREAD

**Issue by VictorioBerra** [khellang/Middleware#56]
https://github.com/khellang/Middleware/blob/4e38c0762aee9145a8523c77994bf293bbd65777/src/ProblemDetails/ProblemDetailsMiddleware.cs#L197

See https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.clear?view=netframework-4.8#remarks

> The Clear method does not clear header information.

**Comment by khellang** [comment]
You're looking at the documentation for `System.Web.HttpResponse`, i.e. ASP.NET (non-Core). The behavior is different for ASP.NET Core:

https://github.com/aspnet/AspNetCore/blob/f989daca4bc81090e4fc882fbd983be8b0fa84a9/src/Http/Http.Extensions/src/ResponseExtensions.cs#L12-L25

As you can see, it's clearly (no pun intended 😂) clearing the headers 😄
