### ISSUE TITLE
Include details in ProblemDetailsException

### ISSUE THREAD

**Issue by mabead** [khellang/Middleware#57]
As shown [here](https://github.com/khellang/Middleware/blob/4e38c0762aee9145a8523c77994bf293bbd65777/src/ProblemDetails/ProblemDetailsException.cs#L5), the ProblemDetailsException does not initialize the `Exception.Message` and does not overwrite `Exception.ToString()`. As a result, it is very hard to log these exceptions in a generic way. 

For example, we have a generic middleware that logs all exception. It simply logs them using the standard ASP.NET Core logger:
```chsarp
_logger.LogDebug(ex, $"Unexpected exception: {ex.Message});
```

Unfortunately, for `ProblemDetailsException` it only prints this:
```
Unexpected exctpion: Exception of type 'Hellang.Middleware.ProblemDetails.ProblemDetailsException' was thrown.`
```
And we don't have any details.

What do you think about initializing the `Message` property using the type and title of the problem details and including all the details in the `ToString()` function? Would you be willing to accept a PR that does that?

**Comment by khellang** [comment]
> What do you think about initializing the `Message` property using the type and title of the problem details and including all the details in the `ToString()` function?

That's probably fine. I've just never thought about it because I just use the exception as a quick way to short-circuit and "smuggle" the problem details out to the middleware.

> Would you be willing to accept a PR that does that?

Yes, please 🙏 Thanks ❤️

**Comment by mabead** [comment]
Pull request opened here: https://github.com/khellang/Middleware/pull/58

**Comment by khellang** [comment]
Closed with #58

**Comment by mabead** [comment]
@khellang Please let me know once you publish an updated nuget package.

**Comment by khellang** [comment]
@mabead Pushed [v3.1.0](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails/3.1.0). It's still validating, but will probably be listed Very Soon™. Thanks again! ✨
