### ISSUE TITLE
Changelog/Release Notes?

### ISSUE THREAD

**Issue by VictorioBerra** [khellang/Middleware#59]
When I update NuGets i go through each package and i go to GitHub and try to find a changelog or release notes.

This way, I can see if the package updates will break my code, or if a feature has been introduced that I can take advantage of to simplify my code.

Going through the commits takes a ton of time. Is there a Changelog.md? Why are there no notes on the releases?

**Comment by khellang** [comment]
> Is there a Changelog.md? Why are there no notes on the releases?

I just haven't written anything up. Going through commits should be really quick. It's more or less one commit == one release. Just look for "version bump" or similar.
