### ISSUE TITLE
Prevent conversion of 401 "Challenge" response to ProblemDetails

### ISSUE THREAD

**Issue by KorsG** [khellang/Middleware#6]
Hi

I was running into some issues with the "ProblemDetailsMiddleware", since it converts 401 Challenge respones into a ProblemDetails responses and thereby removing the "WWW-Authenticate" header in the process.

I have solved it by adding the following check to the "IsProblem" method in "ProblemDetailsMiddleware.cs":
`            
if (context.Response.Headers.ContainsKey("WWW-Authenticate"))
{
    return false;
}
`

Would you be open to implement this, or maybe make some kind of option available to extend the "IsProblem" check?

**Comment by KorsG** [comment]
Yes, adding it to the header exclude list also seems to work, and I don't think it causes any issues to return something in the body... at least I couldn't find anything about it in the RFC, and since it works (although in my very limited test in Chrome), I think it would be preferable to put it in the exclude list and return the ProblemDetails in the body.

Regarding other headers, I can at the moment only think of HSTS: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security.

Maybe the exclude list should be part the options object and by default contain CORS, WWW-Authenticate and HSTS headers, but then it is up to the user to either add or maybe even remove headers they don't want excluded?

**Comment by khellang** [comment]
I've released [v1.1.0 on NuGet](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails/1.1.0). Thanks for the issue!

**Comment by KorsG** [comment]
Awesome! 😃 and thank you for implementing it so quickly 👍
