### ISSUE TITLE
ProblemDetailsMiddleware not working at all with CompatibilityVersion.Version_2_2

### ISSUE THREAD

**Issue by Karql** [khellang/Middleware#60]
Hi!

I've found a bug? with compatibility set to version 2.2
` services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2)`
I have 2.2.6 installed.

Response is started before Invoke method from ProblemDetailsMiddleware 

```c#
public async Task Invoke(HttpContext context)
{
    try
    {
        await Next(context);

        if (Options.IsProblem(context))
        {
            if (context.Response.HasStarted)
            {
                Logger.ResponseStarted();
                return;
            }
            
            ClearResponse(context, context.Response.StatusCode);

            var details = GetDetails(context, error: null);

            await WriteProblemDetails(context, details);
        }
    }
    // ...
}
```

IsProblem also always resturns false because ContentType is already set (what is funny to application/problem+json)

```c#
private static bool IsProblem(HttpContext context)
{
    if (context.Response.StatusCode < 400)
    {
        return false;
    }

    if (context.Response.StatusCode >= 600)
    {
        return false;
    }

    if (context.Response.ContentLength.HasValue)
    {
        return false;
    }

    if (string.IsNullOrEmpty(context.Response.ContentType))
    {
        return true;
    }

    return false;
}
```

Maybe for 2.2 there is no need to set headers etc. but only improve returned by framework:
```
{
  "type": "about:blank",
  "status": 500
}
```

to than what was befor:
```
{
  "type": "https://httpstatuses.com/500",
  "title": "Internal Server Error",
  "status": 500,
  "traceId": "0HLOHLQQH7O9E:00000002"
}
```

Best regards,
Mateusz

**Comment by khellang** [comment]
Hmm. I wonder if this is related to the implicit client errors for 2.2. I have to investigate this a bit... 🙈

**Comment by khellang** [comment]
I'm not able to reproduce this. Did you find a way around it?

**Comment by Karql** [comment]
@khellang thanks for investigation ;)

Here you can see this problem https://github.com/Karql/Middleware/tree/issue-60
I've also looked at this once again and found that problem occurs when you SetCompatibilityVersion(CompatibilityVersion.Version_2_2) with ApiController attribute.

![problem_with_compatibility_and_apicontroller](https://user-images.githubusercontent.com/173098/67043118-9d81e680-f129-11e9-988d-05302a4c2a9c.png)
![problem_without_compatibility_or_without_apicontroller](https://user-images.githubusercontent.com/173098/67043127-a07cd700-f129-11e9-90b7-d5fa774e28af.png)

I hope that it helps you.

**Comment by khellang** [comment]
Yeah, so that's because MVC added its own support for problem details in 2.2. If you want to disable it, you need to set the [`SuppressMapClientErrors`](https://github.com/aspnet/AspNetCore/blob/23f3a10965fb70b1ae34c5464d497c71540c998e/src/Mvc/Mvc.Core/src/ApiBehaviorOptions.cs#L56-L75) property to `true`. There's really not much I can do about this 😢
