### ISSUE TITLE
The future of ProblemDetailsMiddleware and Core 3 UseExceptionHandler

### ISSUE THREAD

**Issue by VictorioBerra** [khellang/Middleware#61]
Core 3 is bringing some new exception handling goodies to the middleware pipeline https://www.red-gate.com/simple-talk/dotnet/net-development/asp-net-core-3-0-exception-handling/

My question is, with this new middleware, would we be able to take advantage of that and remove any redundancies in the ProblemDetailsMiddleware?

**Comment by VictorioBerra** [comment]
See things like `App.UseStatusCodePagesWithReExecute("/system/error/{0}");`

**Comment by khellang** [comment]
I'm not sure what's new about these things in 3.0. They've been around for years.

Last time I checked, they wanted to add a way to return JSON responses as opposed to always returning HTML, but that won't nearly cover the use cases for this middleware.

**Comment by khellang** [comment]
I'm not sure there's anything to do about this issue. I'm about to release a new version for .NET Core 3.0, with minimal changes.
