### ISSUE TITLE
Add TraceId to ProblemDetails

### ISSUE THREAD

**Issue by jochenjonc** [khellang/Middleware#62]
On StackOverflow I found the following [topic](https://stackoverflow.com/a/55292489/13278) about ProblemDetails, before finding this solution.

What I miss in this solution is the traceId. I think it would be nice addition.

**Comment by khellang** [comment]
It should be pretty easy to set the `OnBeforeWriteDetails` property to add `traceId` before writing:

```csharp
services.AddProblemDetails(options =>
{
    options.OnBeforeWriteDetails = (ctx, problem) =>
    {
        problemDetails.Extensions["traceId"] = Activity.Current?.Id ?? ctx.TraceIdentifier
    };
});
```

**Comment by MarcusWichelmann** [comment]
Shouldn't the traceId be added to the problem details result by default? ASP.Net Core does include it on 400 responses. Wouldn't it be more consistent if it's included in all error responses then?

**Comment by khellang** [comment]
> Wouldn't it be more consistent if it's included in all error responses then?

It would, but I don't want to be consistent by default. People can choose what they want their details objects should look like outside the RFC itself 😊 It's a two line change to add it 😉

**Comment by MarcusWichelmann** [comment]
Okay, sounds reasonable. :+1:
