### ISSUE TITLE
StatusCodeValidationProblemDetails

### ISSUE THREAD

**Issue by jochenjonc** [khellang/Middleware#63]
In a project I'm working on I introduced the following a class similar to the [StatusCodeProblemDetails](src/ProblemDetails/StatusCodeProblemDetails.cs) but then inheriting from ValidationProblemDetails.

```csharp
public class StatusCodeValidationProblemDetails : ValidationProblemDetails
{
	public StatusCodeValidationProblemDetails(int statusCode)
	{
		Status = statusCode;
		Type = $"https://httpstatuses.com/{statusCode}";
		Title = ReasonPhrases.GetReasonPhrase(statusCode);
	}
}
```

The reason I did this had to do with the return type of a BadRequest. On the actions of my controllers where I return a BadRequest I set the following attribute.

```csharp
[ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ValidationProblemDetails))]
```

This helps the NSwag/Swagger/Open API 3 generation in creating the correct specification.

But sometimes additional validation is performed in the controller/action code after the model validation. It is possible to return a BadRequest at that stage in the code.
To produce a correct ProblemDetail it should be based on ValidationProblemDetails and not on ProblemDetails. 

But when I do that I can no longer use StatusCodeProblemDetails, which has the nice feature of filling in Status, Type & Title.

Maybe others face the same issue and would it be nice to have the StatusCodeValidationProblemDetails class part of this library.

Additionally I create my custom ProblemDetails so that I can extra properties for this specific action. I than change the attribute to:

```csharp
[ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(MyCustomProblemDetails))]
```

The MyCustomProblemDetails class inherits from ValidationProblemDetails because that's the only way that my OpenAPI 3 spec is still correct when the ASP.NET Core model validation kicks in and returns a ValidationProblemDetails.
To make it myself easier the MyCustomProblemDetails  inherits from StatusCodeValidationProblemDetails so that Status, Type & Title are always set in the same manner.

**Comment by khellang** [comment]
Hey Jochen! I'm not really sure what you're asking... Do you want to include the `StatusCodeValidationProblemDetails` class in the library?

IMO it's a super simple class that's really easy to write yourself and since it would really serve a purpose in the library (other than shipping it to the world), I'm pretty hesitant to include it.

**Comment by jochenjonc** [comment]
Yes, that was my question exactly, but I understand your opinion. I'll include it in my own library then.

It was just that I see your library as adding the missing pieces in the standard implementation. And the standard implementation has two types of ProblemDetails (ProblemDetails & ValidationProblemDetails) so I wanted to ask it first before adding it elsewhere.

**Comment by khellang** [comment]
> I'll include it in my own library then.

Yes, that makes more sense to me. Thanks for the suggestion, though 😄 Keep 'em coming! ❤️
