### ISSUE TITLE
`throw new ProblemDetailsException..` does include exception details?

### ISSUE THREAD

**Issue by alexdresko** [khellang/Middleware#64]
`throw new ProblemDetailsException(validation);` returns HTTP status code 500, but doesn't include the exception details. I think I get why, but it seems inconsistent with throwing any other exception. 

Thoughts?

**Comment by khellang** [comment]
`ProblemDetailsException` is a special kind of exception for bubbling up an existing `ProblemDetails` object. It will just serialize that existing object, without doing anything special.

**Comment by khellang** [comment]
I'm closing this as there's not really anything actionable here 😄
