### ISSUE TITLE
`return BadRequest();` vs `return BadRequest(something);`.

### ISSUE THREAD

**Issue by alexdresko** [khellang/Middleware#65]
This is probably more of a .NET team question, but you seem to be the expert. :) 

I'm curious why `return BadRequest();` returns problem details, but `return BadRequest(something);` returns whatever is passed in. Obviously, you can derive something from `ProblemDetails` and pass that in, but that seems overly complicated. I wish `return BadRequest(something);` would always return problem details. 

Thoughts?

**Comment by khellang** [comment]
But why would you pass `something`, without `something` deriving from `ProblemDetails` if you really want problem details?

The technical reason why it doesn't work is because MVC will serialize `something` and write it to the body, before the response gets back to the middleware. At that point it's too late for the middleware to start writing.

**Comment by alexdresko** [comment]
> But why would you pass something, without something deriving from ProblemDetails if you really want problem details?

Typically to return additional information about the error. For example, with `return NotFound(...)`, you can include the ID of the record that was not found. 

```
public ActionResult Something(int id)
{
    // if the record can't be found in the database
    return NotFound(id);
}
```

It doesn't make sense that one overload of `NotFound` would act differently from another.

**Comment by khellang** [comment]
> It doesn't make sense that one overload of `NotFound` would act differently from another.

Once you know that once you write to the body stream, it's flushed to the client and no other MW can write to it, it makes sense; one overload contains a body, the other doesn't.

**Comment by alexdresko** [comment]
OKOKOK, I get it now. Thanks! 

I referenced this issue from my [blog post](https://www.alexdresko.com/2019/08/30/problem-details-error-handling-net-core-3/).

**Comment by khellang** [comment]
Nice post! 👏

Yeah, I agree that it needs a bit of intimate knowledge of how MVC and middleware works together og what MVC actually does when returning different results. You could probably write some MVC filters to tweak the behaviors, but I wanted a lower level middleware that works (more or less) without MVC.

BTW, when throwing a `ProblemDetailsException`, you can still avoid the (default) 500 status code by setting the `ProblemDetails.Status` property 😊

**Comment by alexdresko** [comment]
> BTW, when throwing a ProblemDetailsException, you can still avoid the (default) 500 status code by setting the ProblemDetails.Status property 😊

I'll be honest, I can't figure out how to do this. Can you point me an an example or doc? 

Also, I updated the post to this information that was just released with .NET Core 3 Preview 9:

![image](https://user-images.githubusercontent.com/333022/64365966-38dc5380-cfe3-11e9-9901-743d9df6a701.png)

**Comment by khellang** [comment]
You just set this property; https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails.status?view=aspnetcore-2.2#Microsoft_AspNetCore_Mvc_ProblemDetails_Status
