### ISSUE TITLE
Can't pass through Detail field on mapped exception in Production

### ISSUE THREAD

**Issue by callsoft** [khellang/Middleware#68]
I have a Web API in which I'm trying to pass a somewhat more detailed message in production to the caller (so they can relay to the user) when an attempt to email to a user fails.  In this particular request, the email send must be successful for the API operation to successfully complete (i.e. don't generate and change user's password if we can't email them the new password).  When the email fails, I need to tell the caller that we can't generate the password and let them know to check the email config rather than just what it does currently which is:

```
{
    "type": "https://httpstatuses.com/400",
    "title": "Bad Request",
    "status": 400
}
```

I have a map set up as follows, where the exception passed has the message I want to convey:
```
// This will map ArgumentException to the 400 BadRequest status code.
options.Map<ArgumentException>(ex => new ExceptionProblemDetails(ex, StatusCodes.Status400BadRequest) { Detail = ex.Message });
```

I'm expecting that Detail will now contain the message I've passed "Could not send email - check email server configuration"

But the response still does not include the Detail field.  Only if I set  options.IncludeExceptionDetails to true do I see it, but then of  course we are sending all the other exception information that we don't want to leak.

This is what I am trying to achieve:

```
{
    "type": "https://httpstatuses.com/400",
    "title": "Bad Request",
    "detail": "Could not send email - check email server configuration",
    "status": 400
}
```

Is there a clean way to do this?

**Comment by callsoft** [comment]
I did this and it works but not sure if this is the best approach:

```
            // This will map ArgumentException to the 400 BadRequest status code.
            options.Map<ArgumentException>(ex => new Microsoft.AspNetCore.Mvc.ProblemDetails { 
                    Status = StatusCodes.Status400BadRequest, 
                    Type = $"https://httpstatuses.com/{StatusCodes.Status400BadRequest}", 
                    Title = ReasonPhrases.GetReasonPhrase(StatusCodes.Status400BadRequest), 
                    Detail = ex.Message
                });
```

**Comment by khellang** [comment]
Yeah, this is essentially the same issue as https://github.com/khellang/Middleware/issues/53 and #51. You'll have to work around it like you've already done for now, until I can find a good way to fix it.

**Comment by khellang** [comment]
I've pushed a new version v5.0.0-beta.1 to NuGet.org that should hopefully address this problem. It would be awesome if you had time to check it out 😄🙏

**Comment by callsoft** [comment]
Finally got around to upgrading my project to check this out.  It works great, thanks!
