### ISSUE TITLE
Can we have an overload for StatusCodeProblemDetails CTOR?

### ISSUE THREAD

**Issue by VictorioBerra** [khellang/Middleware#69]
In MVC Core you can return `StatusCode(int code, object value)` it would be nice if we could propagate that result up. This would be great in `MapStatusCode`, if you can also have an overload for that which exposes the value too.

**Comment by khellang** [comment]
I'm not really sure if I understand what this means? Do you want to include an additional object in status code results? 🤔

**Comment by VictorioBerra** [comment]
Yes. In mvc you can `return StatusCode(201, new Person())` but with this middleware we can't.

**Comment by khellang** [comment]
But what would that return? This middleware is for returning error responses. If you want to return something else, you need to do that from MVC 😊 Seems to be a bit of overlap with https://github.com/khellang/Middleware/issues/65.

**Comment by khellang** [comment]
I'm not sure if there's anything actionable in here 😅
