### ISSUE TITLE
Exception in DeveloperProblemDetails.GetErrors() while executing the problem details middleware

### ISSUE THREAD

**Issue by cremor** [khellang/Middleware#70]
I sometimes get the following exception in my server log:

```
An exception was thrown attempting to execute the problem details middleware.
System.BadImageFormatException: Invalid directory size.
   bei System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
   bei Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetPdbPath(String assemblyPath)
   bei Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetMetadataReader(String assemblyPath)
   bei Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, Int32 IlOffset)
   bei Microsoft.Extensions.StackTrace.Sources.StackTraceHelper.GetFrames(Exception exception)
   bei Microsoft.Extensions.StackTrace.Sources.ExceptionDetailsProvider.<GetDetails>d__3.MoveNext()
   bei Hellang.Middleware.ProblemDetails.DeveloperProblemDetails.<GetErrors>d__4.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Hellang.Middleware.ProblemDetails.DeveloperProblemDetails..ctor(ExceptionProblemDetails problem, IEnumerable`1 details)
   bei Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.GetDetails(HttpContext context, Exception error)
```

I'm not sure how to reproduce it, but from reading the stack trace I have an idea what might happen:

The top methods of the exception call stack indicate that it crashes while reading a PDB file. The problem I see here is that that class name indicates that it tries to read a portable PDB. But my application is running ASP.NET Core 2.2 on the full .NET Framework 4.7.1 since some used libraries are not available as .NET Core or .NET Standard builds. Those libraries also use non-portable PDB files. So I assume the crash happens because it tries to read a non-portable PDB file assuming it is a portable one.

I'm using ProblemDetails package version 3.1.0.

**Comment by khellang** [comment]
Hmm. That's weird. It's even mentioned in the source:

https://github.com/aspnet/AspNetCore/blob/c84e37f30def9ff0b2d12e877e3de6c283be6145/src/Shared/StackTrace/StackFrame/StackTraceHelper.cs#L59-L61

**Comment by khellang** [comment]
I think I might have to file an issue upstream for this...

**Comment by khellang** [comment]
It should support both portable and "full" PDBs, but the check for portable PDBs is *below* the `GetPdbPath` call:

https://github.com/aspnet/AspNetCore/blob/23596349092f69890c3efe5b8b9005856cc83db2/src/Shared/StackTrace/StackFrame/PortablePdbReader.cs#L74

**Comment by nguerrera** [comment]
Doesn't look like it's gotten to reading any pdbs yet, but throws while reading the dll to get the debug directory info. 

I looker quickly at the code wondering if there was something letting go of the PE memory, but it looks Ok.

The next thing I'd want to try would is to inspect the dll to see if it ia in fact corrupted. Are you able to debug and determine what `assemblyPath` parameter is here? 
Cc @tmat

**Comment by cremor** [comment]
> Are you able to debug and determine what `assemblyPath` parameter is here?

Debugging should be no problem. But since I'm not sure how to reproduce this reliably, I might have to try for some time.

An idea about assembly "corruption": I'm using the [Oracle.ManagedDataAccess library](https://www.nuget.org/packages/Oracle.ManagedDataAccess/). This assembly is obfuscated. Maybe that causes problems?

**Comment by khellang** [comment]
> I'm using the [Oracle.ManagedDataAccess library](https://www.nuget.org/packages/Oracle.ManagedDataAccess/). This assembly is obfuscated. Maybe that causes problems?

Aha! I knew I'd seen that somewhere when Googling for more info on this; https://github.com/tonerdo/coverlet/issues/189

**Comment by cremor** [comment]
I can now confirm that this indeed happens if Oracle.ManagedDataAccess throws an exception. The `assemblyPath` parameter of the method `Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetPdbPath()` is the "Oracle.ManagedDataAccess.dll" in my bin directory.

So I assume this means this is actually a bug in `System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()` and I have to file an issue in dotnet/corefx?


But I think this exception could also be handled better in `ProblemDetailsMiddleware`. Why does it fall back to returning a `StatusCodeProblemDetails` if an `ExceptionProblemDetails` is already available (see [here](https://github.com/khellang/Middleware/blob/c454363a0684ce6bbb47c12835d2024db749e30e/src/ProblemDetails/ProblemDetailsMiddleware.cs#L123-L127))? If it would return the already available `result` in the catch block, the developer would at least still get the exception message and stack trace.

**Comment by khellang** [comment]
> So I assume this means this is actually a bug in System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory() and I have to file an issue in dotnet/corefx?
> Or is the exception fine (since Oracle "broke" the assembly) and should be handled in Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetPdbPath()? Then it would be an issue for aspnet/AspNetCore.

Yeah, I'm thinking it's the latter. I.e. the `PEReader.ReadDebugDirectory()` can't read the binary and correctly throws a BadImageException. Would you like to file an issue or should I?

> Why does it fall back to returning a `StatusCodeProblemDetails` if an `ExceptionProblemDetails` is already available (see [here](https://github.com/khellang/Middleware/blob/c454363a0684ce6bbb47c12835d2024db749e30e/src/ProblemDetails/ProblemDetailsMiddleware.cs#L123-L131))? If it would return the already available `result` in the catch block, the developer would at least still get the exception message and stack trace.

Hmm 🤔 I can't remember what my thinking was at the time. I think it was to avoid directly serializing an instance of `ExceptionProblemDetails`, which includes the `Exception` directly. Some exceptions might serialize easily, some might not.

I think it would be better to wrap it in a `DeveloperProblemDetails` and just pass `Array.Empty<ExceptionDetails>` to not include additional details. That would at least fill in the `detail`, `title`, `instance` and `type` fields:

https://github.com/khellang/Middleware/blob/c454363a0684ce6bbb47c12835d2024db749e30e/src/ProblemDetails/DeveloperProblemDetails.cs#L16-L23

**Comment by cremor** [comment]
> Would you like to file an issue or should I?

Would be nice if you could do it. Otherwise I'll do it on Monday.



> That would at least fill in the `detail`, `title`, `instance` and `type` fields:

So it wouldn't give the stack trace? I'd say that's the most important information about an exception ;)

**Comment by cremor** [comment]
@khellang I forgot about this yesterday. I wanted to start with a small sample now, but I already have problems getting the `ExceptionDetailsProvider` class available in my project. Is that MyGet dev feed really the "official" way to get this class?

**Comment by khellang** [comment]
> Is that MyGet dev feed really the "official" way to get this class?

Yeah, the source packages aren't shipped to NuGet, so there's really no better way to get it 😏

**Comment by cremor** [comment]
I've now created the issue: aspnet/AspNetCore#14609

Did you already decide if you will also handle the exception in ProblemDetails?

**Comment by khellang** [comment]
> Did you already decide if you will also handle the exception in ProblemDetails?

It really depends on how fast it's fixed upstream. Since it's just a source package, I can easily pull the latest from MyGet and ship a new version without making source changes to the middleware itself. I'll see if maybe I can fix it myself and send a PR upstream.

**Comment by cremor** [comment]
Seems like your PR was merged, nice.
But do you have any idea when new packages are created? If I see this correctly, the newest package is from November 2018, which was before the code was moved from the aspnet/Extensions repo to the aspnet/AspNetCore repo.

**Comment by khellang** [comment]
I've pushed 4.0.0-beta.1 to NuGet. Let me know if that fixes your issue 👍

**Comment by cremor** [comment]
Works fine, thanks!
