### ISSUE TITLE
Use ILoggerFactory and create Logger with current action name

### ISSUE THREAD

**Issue by NickSevens** [khellang/Middleware#71]
Currently the ILogger category is the name of the Middleware.
Can it be changed so that the CategoryName is set to be the Action of the initial request?
E.g.:
`var logger = loggerFactory.CreateLogger(httpContext.ActionDescriptor.DisplayName);`

**Comment by khellang** [comment]
Not really. That would require MVC to be in the pipeline, which isn't a requirement today. BTW, there's no `ActionDescriptor` property on `HttpContext`.

**Comment by NickSevens** [comment]
Ah yes, indeed, I mistakenly saw it as a HttpContext property - which indeed doesn't make much sense since this lives outside of MVC...
Any chance you see another way to change the logger category name?

**Comment by khellang** [comment]
> Any chance you see another way to change the logger category name?

Not really. What's the issue you're trying to solve?

**Comment by khellang** [comment]
You could try to swap the default logger factory with a version that maps the category to something else?

**Comment by NickSevens** [comment]
We're used to doing some analytics based on (among other things) the category name.
Usually this is controller- or service- based, which would make it more consistent

**Comment by khellang** [comment]
Right, that might make sense if the code is actually in a controller (or service), but if the logging originates in a middleware, I think it makes sense to include that in the logs.

This is the standard way of doing things:

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L33

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/src/Http/Routing/src/RouterMiddleware.cs#L26

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/src/Http/Routing/src/EndpointMiddleware.cs#L25

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/src/Middleware/Session/src/SessionMiddleware.cs#L73

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/src/Middleware/WebSockets/src/WebSocketMiddleware.cs#L45

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L70

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L61

(these were the first 7 ASP.NET Core middlewares I opened in GitHub)

**Comment by NickSevens** [comment]
Valid point it seems ;) Thanks for the input!
Closing the issue.
