### ISSUE TITLE
Invalid TraceId field in the ProblemDetails response

### ISSUE THREAD

**Issue by marcominerva** [khellang/Middleware#72]
Hi!

I'm using ASP.NET Core 3.0 with the last version of Hellang.Middleware.ProblemDetails (3.1.0). In my **Startup.ConfigureServices** method I have added the following line:

`services.AddProblemDetails();`

And the corresponding

`app.UseProblemDetails();`

At the beginning of the **Configure** method.

With this setup, I have noticed that the output is something like this:

```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "Bad Request",
  "status": 400,
  "traceId": "|ce3cd73b-4af1db1e8a67d40f."
}
```

In particular, you can note that the _traceId_ field seems to be invalid. Can you please investigate on this behavior?

**Comment by khellang** [comment]
Hmm. This middleware doesn't really add a `traceId`. There's [an issue to add it](https://github.com/khellang/Middleware/issues/62), but I don't think that'll happen by default.

This is probably from MVC. You have to file an issue with them.

**Comment by khellang** [comment]
The actual code that adds the `traceId` lives [here](https://github.com/aspnet/AspNetCore/blob/8e05fb0cf450afdf629b275435c69c836ae8df68/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L90).

It's basically picking `Activity.Current.Id` or falling back to `HttpContext.TraceIdentifier` if the former is missing. Any one of these could be set externally, so it's hard to tell where the value comes from.

**Comment by khellang** [comment]
In this case, it looks very much like the format of an Activity ID; https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#id-format.

**Comment by marcominerva** [comment]
I see… This seems different from the old format, but that's it. Thank you for your support!

**Comment by khellang** [comment]
It depends on where your request is coming from and whether it includes a `Request-Id` or a `Correlation-Context` header, I think.

Activity also supports [different formats](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activityidformat?view=netcore-3.0), where "hierarchical" is the default. See https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HierarchicalRequestId.md.
