### ISSUE TITLE
Can't build Master or Core 2.2 branch

### ISSUE THREAD

**Issue by NickTholin** [khellang/Middleware#73]
During package restore I receive the following error:

`The package Microsoft.AspNetCore.Authentication.Abstractions.2.2.0 sha512 validation failed. The package is different than the last restore.	ProblemDetails       ProblemDetails.csproj	
`

I have been unable to track it down to successfully build.

**Comment by khellang** [comment]
Are you sure you're on latest master? 🤔 I got the same error and removed the lock file a while ago. See https://github.com/khellang/Middleware/commit/146b736756f0476ef3ca4e3c6f1b3a5eeb62f18d

**Comment by NickTholin** [comment]
You are correct.  I didn't realize I was fetching from my outdated fork.  Mind if I remove the lock file for the core 2.2 branch?  I get the same error in that branch and I'll need to add a default constructor to support xml serialization in 2.2.

**Comment by khellang** [comment]
Hmm. The 2.2 branch is waaaay old and was never really meant to be used for anything. It was just to push a commit for a prototype 😊

**Comment by NickTholin** [comment]
Ok,  I thought I needed to use that branch if I wanted to continue to target .net core 2.2.

**Comment by khellang** [comment]
No, the master branch should still build for netstandard2.0 and depend on ASP.NET Core 2.1 (which is LTS) 😊

**Comment by khellang** [comment]
I'll go ahead and close this as AppVeyor is successfully building the `master` branch :smile:
