### ISSUE TITLE
AddNewtonsoftJson and ProblemDetails, .Net Core 3

### ISSUE THREAD

**Issue by emilssonn** [khellang/Middleware#74]
I am having problems using Newtonsoft as the json serializer (using `AddNewtonsoftJson` in startup) with problem details.
When this package returns the problem details the `Extensions` property is serialzied as `"Extensions": {...}` and not to the parent.
If I in a controller use `return Problem(detail: "test");` the `Extensions` property is serialized correctly.

The `Microsoft.AspNetCore.Mvc.ProblemDetails` has a `JsonExtensionDataAttribute` on the property, but since it is .Net Core 3.0 it is in the namespace `System.Text.Json.Serialization`.

This issue might not be specific for this package but I need to start somewhere.

**Comment by khellang** [comment]
Hi @emilssonn! 👋 

Hmm. The `AddNewtonsoftJson` extension should add a special `ProblemDetailsConverter` that takes care of wrapping `Microsoft.AspNetCore.Mvc.ProblemDetails` in a special wrapper type that utilizes the Newtonsoft.Json-specific `JsonExtensionData` attribute. See https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.NewtonsoftJson/src/ProblemDetailsConverter.cs#L45 and https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.NewtonsoftJson/src/AnnotatedProblemDetails.cs.

I wonder what's going wrong here. Maybe releasing a version targeting `netcoreapp3.0` and the `Microsof.AspNetCore.App` `FrameworkReference` would solve this? @pranavkm?

**Comment by cleftheris** [comment]
> I wonder what's going wrong here. Maybe releasing a version targeting netcoreapp3.0 and the Microsof.AspNetCore.App FrameworkReference would solve this? @pranavkm?

@khellang this is exactly what needs to be done from my experience upgrading my own packages. A package that used to take a dependency on AspNetCore now can only target netcoreapp3.0 with FrameworkReference. 
If you publish a package for early adopters it would be much appreciated (prerelease would do just fine).

Thanks!

**Comment by pranavkm** [comment]
Any chance you could share a minimal app that reproduces the problem? We think adding `AddNewtonsoftJson` should suffice, but it’s also not an area that was tested very well for compatibility.

**Comment by khellang** [comment]
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hellang.Middleware.ProblemDetails" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0" />
  </ItemGroup>
</Project>
```

```csharp
using System;
using System.Threading.Tasks;
using Hellang.Middleware.ProblemDetails;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace NewtonsoftJsonRepro
{
    public class Program
    {
        public static Task Main(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(Configure)
                .Build()
                .RunAsync();

        private static void Configure(IWebHostBuilder builder) => builder
            .ConfigureServices(x => x.AddProblemDetails().AddMvc().AddNewtonsoftJson())
            .Configure(x => x.UseProblemDetails().Use((_, __) => throw new Exception("BOOM!")));
    }
}

```

Returns the following:

```json
{
  "errors": [
    {
      "message": "BOOM!",
      "type": "System.Exception",
      "raw": "...",
      "stackFrames": [...]
    }
  ],
  "type": "https://httpstatuses.com/500",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "BOOM!",
  "instance": null,
  "extensions": {
    
  }
}
````

Removing the call to `AddNewtonsoftJson` will return what you'd expect:

```json
{
  "errors": [
    {
      "message": "BOOM!",
      "type": "System.Exception",
      "raw": "...",
      "stackFrames": [...]
    }
  ],
  "type": "https://httpstatuses.com/500",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "BOOM!",
  "instance": null
}
```

**Comment by khellang** [comment]
When I think about it, the current solution wouldn't allow serialization of sub-types anyway, since the entire thing is wrapped in an `AnnotatedProblemDetails`. All additional properties would get lost when serializing with Newtonsoft.Json.

**Comment by emilssonn** [comment]
@khellang Maybe a temporary fix for people that need to use Newtonsoft.Json is to create converters and `AnnotatedProblemDetails` for the 3 types of ProblemDetails used in this solution? Basically copying (and modifying) `ValidationProblemDetailsConverter`/`ProblemDetailsConverter `, `AnnotatedProblemDetails` from AspNetCore and adding the missing properties.

**Comment by khellang** [comment]
Yeah, I think that's what I need to do. I would still consider not being able to serialize types deriving from `ProblemDetails` with Newtonsoft.Json a bug in MVC though.

**Comment by pranavkm** [comment]
> I would still consider not being able to serialize types deriving from ProblemDetails with Newtonsoft.Json a bug in MVC though.

AFAIK, the check we had was to allow the more specific `ValidationProblemDetailsConverter` to be used for `ValidationProblemDetails`. But feel free to file a bug, we could have a look at what we could do here.

**Comment by khellang** [comment]
I've pushed a new version, v5.0, to NuGet, where I've removed all internal usage of custom sub-types in the middleware. Hopefully this means that the built-in converters should wrap the instances in `AnnotatedProblemDetails` and make Newtonsoft.Json pick up the attributes 🤞
