### ISSUE TITLE
ValidationErrors with ProblemDetails

### ISSUE THREAD

**Issue by veikkoeeva** [khellang/Middleware#75]
Hi!

Hopefully the right place to ask for advice. I added [ProblemDetails Nuget](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails) and thought I configured it correctly. Apparently not and it also appears I don't see the problem myself.

The problem is that I can't get the validation errors come through properly.

So, after adding the library I configure it what I think is fairly normal way and add by just copying the example piece of code from the repository. I also add `options.OnBeforeWriteDetails = (ctx, details) =>` to change some details. The configuration happens at https://github.com/veikkoeeva/orleans/blob/8a44d947660ebc0d3579d175736946b8e113e3be/Samples/OneBoxDeployment/src/OneBoxDeployment.Api/Startup.cs#L387.

Though when I start the service and once it has been opened to the Swagger page and I call https://github.com/veikkoeeva/orleans/blob/update-oneboxdeployment-to-core3/Samples/OneBoxDeployment/src/OneBoxDeployment.Api/Controllers/BigSampleController.cs#L55 with `int` changed to `string` to get a validation error, the lambda isn't called, and the details haven't been changed. And I don't know what gives!

I have also a test that checks some of the contents at https://github.com/veikkoeeva/orleans/blob/update-oneboxdeployment-to-core3/Samples/OneBoxDeployment/test/OneBoxDeployment.IntegrationTests/Tests/FaultInjectionTests.cs#L50.

I also noticed that if `[Produces("application/json", "application/problem+json")]` is provided on the controller level, the return content-type will `application/json` whereas if nothing is given, it will be `application/problem+json`. Is this on purpose? See at https://github.com/veikkoeeva/orleans/blob/update-oneboxdeployment-to-core3/Samples/OneBoxDeployment/src/OneBoxDeployment.Api/Controllers/BigSampleController.cs#L18.

I'm updating the sample to Orleans repo, credit naturally given to those with advice (or commits). :)

**Comment by khellang** [comment]
The issue is probably that MVC is implicitly writing a `ValidationProblemDetails` response when validation fails. This is done by default for all controllers with the `ApiController` attribute, through a filter called `ModelStateInvalidFilter`.

**Comment by veikkoeeva** [comment]
@khellang Apologies for the hiatus. What you suggest would be the right remedy in that case? I have
```
services
    .AddProblemDetails(ConfigureProblemDetails)
    .AddMvcCore(options =>
```
and I would like to set some details like
```
options.OnBeforeWriteDetails = (ctx, details) =>
            {
                var identifier = Guid.NewGuid().ToString();
                ctx.TraceIdentifier = identifier;
                details.Instance = $"urn:oneboxdeployment:error:{identifier}";
            };
```
but for some reason the code isn't being run (copied from https://github.com/veikkoeeva/orleans/blob/update-oneboxdeployment-to-core3/Samples/OneBoxDeployment/src/OneBoxDeployment.Api/Startup.cs#L388). I begin suspect I'm blind or it's a bad thing to hack this during the night. :D

This is slightly tangential, I just updated the sample so the hashes are off. The main thing was to make OpenAPI specification show `application/problem+json` for HTTP 400 Bad Request response.

**Comment by khellang** [comment]
To fix this issue, you probably have to configure MVC to stop mapping client errors to ProblemDetails responses, like this:

```csharp
services.AddControllers(controllers =>
{
    controllers.ConfigureApiBehaviorOptions(api =>
    {
        // Let the ProblemDetails middleware handle error mapping.
        api.SuppressMapClientErrors = true;
    });
});
```
