### ISSUE TITLE
[Question]: When v4.0.0 with .NET Core 3 support leaves the beta channel?

### ISSUE THREAD

**Issue by danielang** [khellang/Middleware#76]
Is there any Roadmap or release date for the v4? 🙂 
Thank you!

**Comment by khellang** [comment]
Not really. If I don't get any issue reports, I'll probably release a non-beta soon.

**Comment by bigdnf** [comment]
What is the status of v4? - I would like to use it in my project but preview is not very welcome ;)

**Comment by khellang** [comment]
> What is the status of v4? - I would like to use it in my project but preview is not very welcome ;)

The status is that the beta has been downloaded over a thousand times and there hasn't been any issues reported 😃I guess I should just go ahead and remove the prerelease suffix and release the new version.

**Comment by khellang** [comment]
Just pushed v4.0.0. Hopefully that will make more people upgrade and report potential issues 😉
