### ISSUE TITLE
ProblemDetails: support derived types in Map<TException>

### ISSUE THREAD

**Issue by StevenLiekens** [khellang/Middleware#8]
It's not currently possible to create a map for an exception type and all its derived types.

```csharp
options.Map<Exception>(e => /* only runs if typeof(e) is exactly Exception */);
```

This means that you can't map an abstract exception class. You can map each individual derived exception type, but you can't pre-configure maps for exception types that haven't been invented yet.

Consider adding a flag to enable mapping derived types.

```csharp
public void Map<TException>(Func<TException, MvcProblemDetails> mapping, bool includeDerived = false) where TException : Exception
```

**Comment by khellang** [comment]
Agreed. I think we should just make it the default. The order in which you register the mapping would determine which mapping is used, i.e.

```csharp
options.Map<Exception>(e => /* will always be used */);
options.Map<InvalidOperationException>(e => /* will never be reached */);
```

vs

```csharp
options.Map<InvalidOperationException>(e => /* will handle all exceptions assignable to InvalidOperationException */);
options.Map<Exception>(e => /* acts as a catch-all mapping */);
```

**Comment by StevenLiekens** [comment]
Alright if you're okay with releasing a breaking change.

**Comment by khellang** [comment]
> Alright if you're okay with releasing a breaking change.

I'll just bump the major version and put it in some release notes. No hassle 😉

**Comment by khellang** [comment]
Pushed [v2.0.0](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails/2.0.0) 😄

**Comment by StevenLiekens** [comment]
Wow you're right on top of things

**Comment by khellang** [comment]
> Wow you're right on top of things

Gotta give the people what they want 😉

**Comment by StevenLiekens** [comment]
I appreciate it, I think this middleware does everything I need now (and saved me a bunch of time)
