### ISSUE TITLE
unable to find package Microsoft.DiaSymReader.Pdb2Pdb on local build

### ISSUE THREAD

**Issue by JonasSamuelsson** [khellang/Middleware#80]
When I build locally I get an error saying `Unable to find package Microsoft.DiaSymReader.Pdb2Pdb`.
The build is still reported as successful & I can run all test but something must be wrong. Does anyone else see the same thing or is it just me. I get it on two different machines.

**Comment by JonasSamuelsson** [comment]
Same issue on AppVeyor https://ci.appveyor.com/project/khellang/middleware/builds/30096685

**Comment by khellang** [comment]
I'm able to reproduce this locally (even with a clean checkout and emptied caches), but seems like https://github.com/khellang/Middleware/commit/62f3510dd5aba44e8e0061503bf1d3b54f6934c7 solved it, at least on AppVeyor.
