### ISSUE TITLE
Configure output of 'Request already started'

### ISSUE THREAD

**Issue by mschmidt98** [khellang/Middleware#82]
Hi Kristian,

We are using your problem details middleware together with `aspnetcore`'s built in model validation, which is activated implicitly by adding the ApiControllerAttribute to our web api controller.

When sending a request, that causes model validation to fail, it seems asp cancels the request before reaching the `ProblemDetailsMiddleware` (which is fine, because we want to return `422 Unprocessable Entity` in that case). Your code checks this and outputs "The response has already started" into the log.

Because our web api is part of quite a large eco system with multiple services, and the api is supposed to serve as an interface to third party applications, I'm afraid this might spam the logs and  cause confusion to customers reading the log files.

We use a custom Filter to influence the response format, but even if we disable the filter, this 'problem' still occurs.

Is it possible, to configure/disable this "response already started" message, or do you have any other workaround?

Thanks in advance,
Markus

**Comment by khellang** [comment]
> Is it possible, to configure/disable this "response already started" message, or do you have any other workaround?

There's no way to configure it outside ASP.NET Core's logging configuration, no.

If you're not interesting in seeing this, you probably want to just filter the message away, using [ASP.NET Core's Log Filtering](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-filtering). If you configure `Hellang.Middleware.ProblemDetails` to have a minimum log level of `Error`, you should be able to get rid of that message, while still keeping the rest of the logging (all remaining logs [are errors](https://github.com/khellang/Middleware/blob/024c508a7cd94a29b43419b039517f0807b60feb/src/ProblemDetails/LoggerExtensions.cs#L8-L15))

**Comment by mschmidt98** [comment]
Hi again,
Could have thought about using the MS Log filter myself.
That eventually did the trick. Many thanks for the quick response :)
