### ISSUE TITLE
ProblemDetails and Rethrow Exception

### ISSUE THREAD

**Issue by bopazyn** [khellang/Middleware#85]
Is it possible to rethrow handled Exception?

Imagine having this middlewares structure:
```
 public void Configure(IApplicationBuilder app)
 {
    app.UseAllElasticApm(Configuration);
    app.UseProblemDetails();
    app.UseMvc();
}
```

Can `ProblemDetailsMiddlware`  transform response into RFC 7807 standard and also rethrow exception that ElasticApmMiddleware could handle it?

**Comment by khellang** [comment]
I guess it could. It would just be a matter of removing [this `return` statement](https://github.com/khellang/Middleware/blob/7e4943b6153e2ffb4eabe3b53b4bede3345cb54f/src/ProblemDetails/ProblemDetailsMiddleware.cs#L94). Maybe we could introduce an option for ti?

**Comment by bopazyn** [comment]
I can prepare PR in few days.
