### ISSUE TITLE
Improve rethrow logic

### ISSUE THREAD

**Issue by bopazyn** [khellang/Middleware#87]
I am thinking of introducing two new methods for `ProblemDetailsOptions` class:

- `Rethrow<T>() where T:Exception`
- `Rethrow<T>(Func<HttpContext, Boolean> predicate) where T:Exception`

The logic would run before `ShouldRethrowException`.

**Comment by khellang** [comment]
Hmm, in that case, I think we should just remove `ShouldRethrowException` altogether (it hasn't shipped yet) as it would allow you to misconfigure the middleware.

**Comment by bopazyn** [comment]
You are right. Having both would `ShouldRethrowException` and `Rethrow` would introduce many errors because the logic isn't obvious.

I can preapare PR in few days.

**Comment by bopazyn** [comment]
PR was successfully merged into master.
