### ISSUE TITLE
Request: .d.ts for TypeScript

### ISSUE THREAD

**Issue by DaleyKD** [khellang/Middleware#90]
I am by no means an expert with TypeScript (I find that most of my knowledge of it is now considered _legacy_), but when consuming errors in JavaScript/TypeScript after making an `$.ajax()` call, it'd be nice to be strongly typed.

I think I made a .d.ts that suffices, but it'd be neato-roony to have an official one.

Thanks for the consideration.

**Comment by khellang** [comment]
Hi @DaleyKD! 👋 

I'm not sure I understand how that fits into this project?
Are you asking for official TS definitions for RFC7807? 🤔

**Comment by DaleyKD** [comment]
I totally understand why it may be/seem outside the scope of this project.

I suspect an official RFC7807 TS definition would be a great start, for sure.  But I'm also including your extensions for the following https://github.com/khellang/Middleware/blob/master/src/ProblemDetails/DeveloperProblemDetails.cs, including `ErrorDetails` and `StackFrame`.

Like I said, I made my own, but thought if I could `npm -i @types/_____ --save-dev`, it'd help make things a hair easier than copying/pasting my own .d.ts for every project.

**Comment by khellang** [comment]
Hey @DaleyKD! Since I'm not using TS much myself, I don't think this repo is the best place for such type definitions.

If you were to push a package to NPM with yours, that would be awesome. I'd gladly link to them from this repo as well 😄
