### ISSUE TITLE
DeveloperProblemDetails ignores Extensions data

### ISSUE THREAD

**Issue by shatl** [khellang/Middleware#91]
Version: 4.2.0

`DeveloperProblemDetails` constructor does not copy Extensions data from existing `ExceptionProblemDetails` 

Reference to constructor
https://github.com/khellang/Middleware/blob/v4.2.0/src/ProblemDetails/DeveloperProblemDetails.cs#L25

**Comment by khellang** [comment]
Indeed. The extension data wasn't there in 2.0/2.1, so I'd have to `#ifdef` it in. I've actually been wanting to get rid of `DeveloperProblemDetails` for a while, as it removes all extra properties that a subclass of `ProblemDetails` might have. I just happened to publish a beta version today with the new behavior. It would be cool if you were able to take that for a spin and see if it works for you. BTW, it only supports netcoreapp3.1.

**Comment by shatl** [comment]
Unfortunately I'm still on 2.2.
I can raise a pull request for 4.2, if you fine with releasing 4.2.1

**Comment by khellang** [comment]
Yeah, that would be fine 👍

**Comment by shatl** [comment]
Could you create branch from v4.2.0 tag so I target PR to it?

Thanks!

**Comment by khellang** [comment]
I've pushed a [`4.x`](https://github.com/khellang/Middleware/tree/4.x) branch you can target 😄

**Comment by shatl** [comment]
Done

**Comment by khellang** [comment]
Pushed v4.3.0 with your changes. Thanks! 😘
