### ISSUE TITLE
No error tag is set when using OpenTracing.Contrib.NetCore with Hellang.Middleware.ProblemDetails

### ISSUE THREAD

**Issue by szmalec** [khellang/Middleware#93]
In my application (.NET Core 3.x) I use [OpenTracing.Contrib.NetCore](https://github.com/opentracing-contrib/csharp-netcore) and [C# tracing client for Jaeger](https://github.com/jaegertracing/jaeger-client-csharp). When unhandled exception occurs, the `OpenTracing NetCore` sets the so-called open tracing **error tag**, making it easy to find error traces in [Jaeger UI](https://github.com/jaegertracing/jaeger-ui):

![jaeger_ui](https://user-images.githubusercontent.com/7856921/77172781-d6e6c580-6abe-11ea-919f-cd25747a157a.png)

**Unfortunately, when I started to use Hellang.Middleware.ProblemDetails package, error tags are not set anymore in case of unhandled exception.**

I thought that the solution to the problem could be to manually set the error tag (keyword is [SetException](https://github.com/opentracing-contrib/csharp-netcore/search?q=SetException&unscoped_q=SetException)) in `OnBeforeWriteDetails` (similarly as in [one of example projects in which someone tried to "integrate" the tracing related item (traceId) with Hellang.Middleware.ProblemDetails](https://github.com/christianacca/ProblemDetailsDemo/blob/master/src/ProblemDetailsDemo.Api/ProblemDetailsConfig/ProblemDetailsOptionsCustomSetup.cs#L34)... 

Unfortunately, I have no idea how to get to the exception object, because the `details` parameter in `OnBeforeWriteDetails `does not have a field from which this object could be taken (it is of type `Microsoft.AspNetCore.Mvc.ProblemDetails` - during the debug session I see that it is actually an internal `Hellang.Middleware.ProblemDetails.DeveloperProblemDetails` type)...

From what I can see in `Hellang.Middleware.ProblemDetails.ProblemDetailsOptions` - it contains properties in which `Exception` object can be accessed (e.g. in [ShouldLogUnhandledException](https://github.com/khellang/Middleware/blob/v4.2.0/src/ProblemDetails/ProblemDetailsOptions.cs#L44)) but I don't think this is a good place to do logic from [SetException()](https://github.com/opentracing-contrib/csharp-netcore/blob/v0.6.2/src/OpenTracing.Contrib.NetCore/Internal/SpanExtensions.cs#L13) in these places.

For now I have temporarily solved the problem in the following (very ugly) way:

```C#
using OpenTracing;
using OpenTracing.Tag;

// ...

private const string ErrKey = "_errObjectForSetException";
private readonly ITracer _tracer;

// ...

options.ShouldLogUnhandledException = (ctx, error, d) =>
{
    ctx.Items[ErrKey] = error;

    // Condition taken from  https://github.com/khellang/Middleware/blob/v4.2.0/src/ProblemDetails/ProblemDetailsOptionsSetup.cs#L26
    return !d.Status.HasValue || d.Status.Value >= 500;
};

options.OnBeforeWriteDetails = (ctx, details) =>
{
    var traceId = Activity.Current?.Id ?? HttpContextAccessor.HttpContext.TraceIdentifier;
    details.Extensions["traceId"] = traceId;

    if (_tracer.ActiveSpan != null)
    {
        var err = ctx.Items[ErrKey] as Exception ?? new Exception(details.Detail);
        _tracer.ActiveSpan.SetTag(Tags.Error, true);
        _tracer.ActiveSpan.Log(new Dictionary<string, object>(3)
        {
            { LogFields.Event, Tags.Error.Key },
            { LogFields.ErrorKind, err.GetType().Name },
            { LogFields.ErrorObject, err }
        });
    }
};
```

**Is there a better way to solve this problem?**
Maybe `OnBeforeWriteDetails` can have an additional parameter with `Exception` object (with null when `OnBeforeWriteDetails` called in [try code block](https://github.com/khellang/Middleware/blob/v4.2.0/src/ProblemDetails/ProblemDetailsMiddleware.cs#L71) and non-null value when called in catch code block of `ProblemDetailsMiddleware`)?

**Comment by khellang** [comment]
> Unfortunately, when I started to use Hellang.Middleware.ProblemDetails package, error tags are not set anymore in case of unhandled exception.

Why did it stop setting error tags? Because the middleware catches exceptions? What if you set `ShouldRethrowException` and just return `true` to make the exception bubble up to the tracing middleware?

**Comment by szmalec** [comment]
That's what I needed! As you said, the reason was that middleware catches the exception.

By using [`Rethrow<Exception>()`](https://github.com/khellang/Middleware/blob/v4.2.0/src/ProblemDetails/ProblemDetailsOptions.cs#L62), the `Exception` object can be used [somewhere at the end of the HTTP request processing](https://github.com/dotnet/aspnetcore/blob/v3.1.0/src/Hosting/Hosting/src/Internal/HostingApplication.cs#L94) - where [diagnostic event is triggerred](https://github.com/dotnet/aspnetcore/blob/v3.1.0/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L127). This event is then [processed in `OpenTracing.Contrib.NetCore`](https://github.com/opentracing-contrib/csharp-netcore/blob/v0.6.2/src/OpenTracing.Contrib.NetCore/AspNetCore/HostingEventProcessor.cs#L69) (this is where the [error tag](https://github.com/opentracing/specification/blob/1.1/semantic_conventions.md) is set).

By the way - debugging this case, I discovered that `OpenTracing.Contrib.NetCore` also does not set the error tag if we use `app.UseDeveloperExceptionPage(); `- I think in that scenario ["Microsoft.AspNetCore.Diagnostics.UnhandledException" event is raised](https://github.com/dotnet/aspnetcore/blob/v3.1.0/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L115) instead of expected one (`"Microsoft.AspNetCore.Hosting.UnhandledException"`).

Now I see that I should analyze project closed issues more carefully, because [someone had quite similar problem](https://github.com/khellang/Middleware/issues/85) ;)

Thank you for support!

**Comment by khellang** [comment]
Nice. Yes, it's a fairly new feature contributed by @bopazyn. Awesome that it solved it for you 😎👌
