### ISSUE TITLE
Weird interaction between `UseProblemDetails` and Serilog's `UseSerilogRequestLogging`

### ISSUE THREAD

**Issue by alexdresko** [khellang/Middleware#94]
First, I want to say that I'm not sure if this is a problem with `UseProblemDetails` or [`UseSerilogRequestLogging`](https://github.com/serilog/serilog-aspnetcore#request-logging).  But I'm pretty sure I've got a few new gray hairs trying to figure this out and I need to create an issue somewhere. If this is deemed to be a Serilog problem, I'll take this discussion over there. 

Plus, @khellang is a great guy and is always responsive to issues... So Imma start where I'm comfortable. :) 

In short, with both `UseProblemDetails` and `UseSerilogRequestLogging` in place, my API properly converts exceptions into, say, HTTP 404 problem details as configured:

![image](https://user-images.githubusercontent.com/333022/77467859-14ab5d00-6de3-11ea-9a05-03162a369971.png)

That's good. 

However, when with `UseSerilogRequestLogging` in place, that same request shows up as HTTP 500 in Serilog's output (I'm using Seq):

![image](https://user-images.githubusercontent.com/333022/77468090-7bc91180-6de3-11ea-8007-74692c594af7.png)

The stack seems to show that there's some implicit interaction between the two middlewares. `UseProblemDetails` seems to be the initiator, but obviously `UseSerilogRequestLogging` is what triggers the unwanted change. If I remove `UseSerilogRequestLogging`, everything works as expected, sans whatever `UseSerilogRequestLogging` does. I only have that line of code in the application because that's what the instructions say to do. I don't know what `UseSerilogRequestLogging` actually does.  

[This post](https://nblumhardt.com/2019/10/serilog-mvc-logging/) may be of some help -- sentence "Because the UseSerilogRequestLogging() middleware runs in the request handling pipeline outside of ASP.NET Core MVC, the request completion event doesn’t include MVC-specific details like ActionId or ActionName by default." seems suspect. But this is all well outside my realm. 

[Here's a repro](https://github.com/khellang/Middleware/files/4377288/WebApplication31.zip) if you need it. You'll need [Seq](https://datalust.co/download) to view the output (or I can change the repro to log to a file). Simply [un]commenting `UseSerilogRequestLogging` affects the output. When the site is running, just hit http://localhost:6215/api/test/d in your browser to trigger the exception. There are a few more API methods in the controller for testing related interactions. 

It doesn't seem like the order of the two middlewares matters, less I messed that test up. 

I hope all of that makes sense. I'll make myself readily available to answer questions. 

Thank you SO much for your time!

**Comment by khellang** [comment]
I think that's to be expected. Serilog hardcodes 500 as the status code whenever it logs an exception:

https://github.com/serilog/serilog-aspnetcore/blob/d9087b65249af4b55afd7b10c1ad10fdc605c881/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L65

If you don't want to have Serilog log exceptions, you should try swapping the order between `UseProblemDetails` and `UseSerilogRequestLogging` to make the problem details middleware transform the exception to a response first, then have Serilog log it.

**Comment by khellang** [comment]
However, if you *do* want exceptions to be logged by Serilog (which I expect you might), you still need to have Serilog as the very first middleware in the pipeline, but with two additional changes:

1. Call `Rethrow<Exception>()` on the problem details options to make sure exceptions bubble up to the Serilog middleware after being converted to a response.
2. Change the Serilog middleware to respect the actual response status code

**Comment by alexdresko** [comment]
Thanks for the great feedback! I'll report back with my findings.

**Comment by khellang** [comment]
Hey @alexdresko!

Did you get to test swapping the order of the Serilog and ProblemDetails middlewares?

**Comment by alexdresko** [comment]
I wasn't able to last week :( but Imma take a stab at it this morning.

**Comment by khellang** [comment]
I don't think there's anything for me to do on this issue 😄

**Comment by alexdresko** [comment]
For the record, I just took another stab at this. [Taking the conversation](https://github.com/serilog/serilog-aspnetcore/issues/187) over to the Serilog repo to see if someone there can point a finger in the right direction.  Will update this issue if/when I get somewhere. 

Thanks again for your time!

**Comment by khellang** [comment]
If you didn't see it, we already had a conversation there 😅 https://github.com/serilog/serilog-aspnetcore/issues/185

**Comment by bartpio** [comment]
For what it's worth, I created a [package](https://github.com/bartpio/problemdetails-serilog-connector) that aims to make `UseProblemDetails` and `UseSerilogRequestLogging` play well together, with the end result being that Serilog logs the correct status code and exception details at the completion of the request, and ProblemDetails is relieved of exception logging duties (while continuing to catch exceptions, without re-throwing).

Serilog decides on a log level based on the final http status code (as decided by ProblemDetails). This can be configured using Serilog's `RequestLoggingOptions.GetLevel` callback. The default behavior is that status codes of 500 or greater result in an error being logged; otherwise, an information-level message is logged. The default behavior also considers any exception still flying at the time it reaches Serilog middleware to be an error, which is not relevant here, as ProblemDetails catches exceptions before they get to Serilog.
