### ISSUE TITLE
Not all exceptions should be converted to ProblemDetails

### ISSUE THREAD

**Issue by Yaevh** [khellang/Middleware#95]
Right now, `ProblemDetailsOptions.IsProblem()` is invoked to check whether the response should be converted to ProblemDetails, but unhandled exceptions are always converted to `ProblemDetails`. 

I want to limit this behaviour and convert only some exceptions to `ProblemDetails`, with others handled by other means (e.g. exceptions from JSON API routes should be converted to ProblemDetails, but exceptions from regular HTML routes should display error page).

Right now the only way I can think of to achieve this behaviour is to implement `ProblemDetailsOptions.OnBeforeWriteDetails` and throw an exception inside it; this inner exception then gets swallowed, but forces `ProblemDetailsMiddleware` to rethrow the original exception, which can then be handled by another middleware further up the chain. However, that's essentially using exceptions as mechanism for flow control, which is bad for a whole lot of reasons.

will probably submit PR for this.

**Comment by khellang** [comment]
Makes sense. There are two reasons for the current behavior; the middleware was never intended for anything other than APIs and I wanted to make sure those APIs _always_ returned consistent error responses.

I don't really have a problem adding a mechanism for controlling this son version though. 

> will probably submit PR for this.

That would be awesome. What would that look like? Is there an existing mechanism we can leverage to achieve this? I'd like to keep the number of knobs and options as low as possible.

Maybe we can say that if you return `null` from a `Map<TException>` call, we bail out? I'm not even sure we handle nulls in this case today 🤔

**Comment by Yaevh** [comment]
> Maybe we can say that if you return null from a Map<TException> call, we bail out? I'm not even sure we handle nulls in this case today
We don't, returning null from `Map<TException>()` causes NRE in `WriteProblemDetails()`. However, I don't particularly like the idea of returning `null` from `Map<TException>()` - it's not intuitive and to me it looks almost as magical as throwing exception in `OnBeforeWriteDetails()` :)

The most intuitive and easy-to-use way would IMHO be to introduce another knob in `ProblemDetailsOptions`, something like `Func<HttpContext, Exception, Microsoft.AspNetCore.Mvc.ProblemDetails, bool> ShouldHandleException`, similar to `ShouldLogUnhandledException`.

**Comment by khellang** [comment]
> We don't, returning null from `Map<TException>()` causes NRE in `WriteProblemDetails()`.

Right, so fixing this bug, we either have to introduce the functionality you're asking for (bail out) or throw a better exception. I'm still thinking the former would work. I'm not a fan of returning `null` in general either, but I was thinking this was an edge case that could maybe be solved without having to introduce a new option.

At the same time, we don't have a way to control exception handling, like we do with status code handling (`Options.IsProblem`), so maybe we should just add it? What about extending `IsProblem` to take an exception as well, and reuse that?

**Comment by Yaevh** [comment]
Initially I thought of using `IsProblem` too, but that would introduce a breaking change, and the `Exception` parameter would have to be optional, which may be confusing for some people; so I'd rather prefer two different methods - one with exception, one without. But that's only my peronal view.

I've also realized that recently a `Rethrow()` option was introduced. Combined with ignoring exceptions this would cause us to have four paths:

1. swallow the exception and write it out as `ProblemDetails` (that's the default)
2. write out the `ProblemDetails` and rethrow the exception (it's now possible with `Rethrow()`)
3. ignore the `ProblemDetails` and let the exception pass through to be handled by a higher-level middleware (basically a `Rethrow()` with `WriteDetails()` suppression)
4. swallow the exception and do nothing (probably not recommended; if you want to swallow all exceptions, you should rather implement some explicit top-level exception handling)

Unless we want to tinker with `Rethrow()` we basically have these options:

1. extend `IsProblem` by adding an `Exception` parameter (which will be null most of the time)
2. add another extension point (`ShouldWriteDetails` maybe?) to `ProblemDetailsOptions`
3. return `null` from `Map<TException>()` to suppress handling of that exception

Seeing that this feature interplays with `Rethrow()`, I'm in favor of the second solution, modeled after `Rethrow()` and `Map()` (`WriteDetails<TException>()` and `WriteDetails<TException>(Func<HttpContext, TException, bool>)`?)

**Comment by khellang** [comment]
> Combined with ignoring exceptions this would cause us to have four paths

Yeah, this is why I want to keep the knobs to a minimum. For every new option introduced, there's _n_ number of new permutations to consider.

I would honestly weigh all other alternatives heavier than adding new options, so I would actually say my preferred order is 3., 1., 2. (or both 3. and 1.).

Alternative 3. (in combination with `Rethrow()`) would basically solve the problem you're having, without any breaking changes, and actually fixing a "bug" at the same time. Sure, it's not the prettiest solutions (returning `null`), but I do think it conveys the intent, i.e. `Map<BlahException>(ctx => null)` -> "this exception shouldn't result in a problem response", and I don't think this is a very common case (no one has asked for it until now, so I'm not sure it deserves its own API just yet). If you think it's ugly having two calls (one to `Map<TException>` and one to `Rethrow<TException>`), you could hide them in an extension method, either in this library or in your own app.

Alternative 1. would probably be the most consistent solution, but it's a breaking change and it's a bit ugly with the exception being `null` most of the time (although this would be documented). It's a rarely used extension point in my experience, so the break probably wouldn't be that bad.

Alternative 2. might be the cleanest, in theory, but as I mentioned, it introduces another set of configuration permutations, and just the naming alone will probably take a while to get right. If possible, I would like to punt on this (at least until more people weigh in on the scenario).

**Comment by khellang** [comment]
I guess we could also default to rethrowing the original exception if you return `null` from a call to `Map`. Honestly I think it leads you into the pit of failure by having a way to silently swallow exceptions.

**Comment by Yaevh** [comment]
I've pushed #96 to 4.x, still need to figure out how to merge it with master
