### ISSUE TITLE
IncludeExceptionDetails Removes "detail" and "errors"

### ISSUE THREAD

**Issue by daviscollins** [khellang/Middleware#97]
We currently using `5.0.0-beta.4`, and have our services configured as follows:
```C#
services.AddProblemDetails(setup => {
    // This block maps exceptions to problem details with appropriate HTTP codes 
    setup.IncludeExceptionDetails = (ctx, ex) => {
        // easier to debug
        var isDevelopment = Env.IsDevelopment();
        return isDevelopment;
    };

    setup.MapToStatusCode<NotImplementedException>(StatusCodes.Status501NotImplemented);
    setup.MapToStatusCode<HttpRequestException>(StatusCodes.Status503ServiceUnavailable);
    setup.MapToStatusCode<ArgumentException>(StatusCodes.Status400BadRequest);
    setup.MapToStatusCode<ArgumentNullException>(StatusCodes.Status400BadRequest);
    setup.MapToStatusCode<CreateFailedException>(StatusCodes.Status400BadRequest);
    setup.MapToStatusCode<DataValidationException>(StatusCodes.Status400BadRequest);
    setup.MapToStatusCode<DeleteFailedException>(StatusCodes.Status400BadRequest);

    setup.MapToStatusCode<SoloException>(StatusCodes.Status500InternalServerError);
    setup.MapToStatusCode<StarkException>(StatusCodes.Status500InternalServerError);
    setup.MapToStatusCode<DbUpdateException>(StatusCodes.Status400BadRequest);

    // Because exceptions are handled polymorphically, this will act as a "catch all" mapping, which is why it's added last.
    // If an exception other than NotImplementedException and HttpRequestException is thrown, this will handle it.
    setup.MapToStatusCode<Exception>(StatusCodes.Status500InternalServerError);
});	
```

When running in a production environment it seems that `detail` and `errors` are being left out of the response. The following are example responses we receive in a dev environment followed by one from a production environment.

Dev:
![beta_dev_true](https://user-images.githubusercontent.com/7423459/77777472-000ad700-7026-11ea-81c8-c942e5dd2834.png)

Production:
![beta_dev_false](https://user-images.githubusercontent.com/7423459/77777482-039e5e00-7026-11ea-9040-7c81c1068f70.png)

Is this excepted behavior of `.MapToStatusCode<>()`? I get the impression that might be the case from the method summary, as it only mentions including the Type and Title from the ProblemDetails class.

I've read through #51, #53, and #68 which seemed to outline similar issues, but based on your comments I expected it to be resolved in the beta version of the package we're using.

Any help or advice would be much appreciated, thanks!

**Comment by khellang** [comment]
> When running in a production environment it seems that detail and errors are being left out of the response.
> Is this excepted behavior of `.MapToStatusCode<>()`?

Yes, indeed, we don't want to leak exception  details and stack traces in a non-development environment. That's why the middleware defaults to only including them when `Environment.IsDevelopment()` is `true`. If you really do want to include details outside the dev environment, you can change `IncludeExceptionDetails` to fit your needs.

I would like to hear what you'd expect from the current setup, and how the current response differs from your expectations.

**Comment by khellang** [comment]
Those other issues you linked is related to earlier versions of the middleware wrapping user-created instances with a special wrapper type for exceptions, which resulted in some information being stripped from the response. These cases were not using `MapToStatusCode`, which is a thin convenience method over `Map` that simply sets the status code, type and title, but explicitly returning custom instances of `ProblemDetails`.

**Comment by daviscollins** [comment]
I believe I've resolved my confusion by configuring each of the exception types as follows:
```C#
setup.Map<NotImplementedException>(ex => new StatusCodeProblemDetails(StatusCodes.Status501NotImplemented) { Detail = ex.Message });
```

This ensures that the Detail property is always present, containing the exception message, regardless of the environment. Our intent is to always return this value, without leaking any other more sensitive info such as the stack trace.

Thanks for the quick response!

**Comment by khellang** [comment]
Nice 😎 Yeah, I don't think it would be responsible to include exception messages (in this library) by default as they can often include sensitive information, but mapping specific exceptions like you've done here is exactly what the mechanism is for 😊 Glad it worked out for you 👌
